### ISSUE TITLE
Request & fix dn.no

### ISSUE THREAD

**Issue by Su-Well** [bpc-clone/bpc_chrome_support#100]
Describe issue/request:
There's a bug that causes an exception when accessing a null element in the no_nhst_media_domains code. This request proposes a simple fix and proposes to add dn.no to the list of no_nhst_media_domains.

The code is fixed by changing the line

`if (par.type) {`

to

`if (par && par.type) {`

after this fix, and after adding dn.no to no_nhst_media_domains, to sites.js and manifest.json, paywall is sucessfully bypassed on dn.no.

Browser (main version): firefox and chrome

BPC-extension version (number): 3.7.1.0

Link of paywalled article: https://www.dn.no/eiendom/new-york-bosatt-hedgefondforvalter-kjopte-giganthytte-pa-kvitfjell/2-1-1660909

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): changed the code. It worked.

**Comment by bpc-clone** [comment]
Good to see that another NHST site moves to the new paywall.\
For all sections though like D2 and Magasin (before they had different paywalls)?

PS example article with null par?

**Comment by Su-Well** [comment]
https://www.dn.no/marked/easee-tapte-over-300-mill-etter-svensk-salgsforbud-det-brant-pa-alle-fronter/2-1-1661166 has null par, in pars[10].

It doesn't seem to work for D2 unfortunately. I'm not sure where to find the Magasin section.

**Comment by bpc-clone** [comment]
Not working for all magasiner: D2 & DN Helg (magasinet).\
Site can be added, but any other sections which need to be excluded?

**Comment by Su-Well** [comment]
smak also doesn't seem to work, but everything else seems to be working

**Comment by bpc-clone** [comment]
Site added to latest master (or next release).\
PS for magasiner articles a link to Google Search Tool (elaborate fix).

**Comment by Su-Well** [comment]
works great, thank you very much.
