### ISSUE TITLE
Please add ledauphine.com

### ISSUE THREAD

**Issue by ghost** [bpc-clone/bpc_chrome_support#104]
Describe issue/request: 
Ledauphine.com doesn't work

Link of paywalled article: 
https://www.ledauphine.com/faits-divers-justice/2024/06/17/ultra-trail-mortel-des-consignes-particulierement-strictes-de-securite-avaient-ete-donnees

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
I think I've tried a lot of things that were within my reach, but nothing works 

Browser (main version): 
Brave 1.67.116

BPC-extension version (number): 
3.7.1.1

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
