### ISSUE TITLE
Request [www.abendzeitung-muenchen.de]

### ISSUE THREAD

**Issue by Amr0077** [bpc-clone/bpc_chrome_support#116]
The newspaper Abendzeitung has implemented a new paywall. If possible, can you add it to your list?

Link of paywalled article: https://www.abendzeitung-muenchen.de/sport/fcbayern/fc-bayern-legende-thomas-helmer-im-az-interview-leroy-sane-da-haette-ich-mir-mehr-erwartet-art-989128

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): yes i tried archive sites but its not working 

Browser (main version): Microsoft Edge Version 126.0.2592.68

BPC-extension version (number): v3.7.1.1

PS always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
You can add the domain as custom site: custom sties > import from online & opt-in to custom sites.
