### ISSUE TITLE
Request [latimes.newspapers.com]

### ISSUE THREAD

**Issue by StarfunkBoogie** [bpc-clone/bpc_chrome_support#119]
Describe issue/request: Request for the LATIMES archive to be added

Link of paywalled article: https://latimes.newspapers.com/image/380696495

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Cookies, useragant, archive sites, reader view, custom site add. None work.

Browser (main version): Chrome

BPC-extension version (number): v3.6.7.6

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
