### ISSUE TITLE
Request/ wn.de and muensterschezeitung.de

### ISSUE THREAD

**Issue by men2050** [bpc-clone/bpc_chrome_support#12]
Describe issue/request: both sites are missing

Link of paywalled article: https://www.wn.de/ & https://www.muensterschezeitung.de/
 

Browser (main version): Chrrome

BPC-extension version (number): 3.6.5.9

**Comment by bpc-clone** [comment]
No fix for both sites (on nofix-list).
PS use issue template: Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).
