### ISSUE TITLE
Bug diariosur.es - Vocento Group

### ISSUE THREAD

**Issue by hubrikt** [bpc-clone/bpc_chrome_support#121]
Describe issue/request: www.diariosur.es (Vocento group) is not working now. It was working flawlessly till yesterday. Now, when opening an error appears
<img width="429" alt="image" src="https://github.com/bpc-clone/bypass-paywalls-chrome-clean/assets/89421789/473fb539-593f-4717-810b-d9bc18dcb0ea">

Link of paywalled article: https://www.diariosur.es/malagacf/rosaleda-perfila-sede-mundial-2030-20240626011508-nt.html

Actions you tried yourself and if it works (clear cookies, disable Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Clear cookies through BPC extension. Also tried directly from browser. When disabled extension, website automatically is loaded without no errors.

Browser (main version): MS Edge 126.0.2592.68 (last version as today)

BPC-extension version (number):   v3.7.2.4  

PS always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Group fixed in latest master/update rules (or next release).

**Comment by hubrikt** [comment]
Thanks, now error disappeared.
However, website format is not the usual one for the paid articles.
Compare this two links using the addon:

**Free article:** https://www.diariosur.es/malagacf/calendario-segunda-division-20242025-malaga-sorteo-20240626161009-nt.html

**Paid article:** https://www.diariosur.es/unicaja/debe-unicaja-retener-yankuba-sima-20240626010416-nt_amp.html

**Comment by bpc-clone** [comment]
Indeed amp-format, but beggars can't be choosers ;-)\
But update reverted in latest master since old fix works again (temporary block?).
