### ISSUE TITLE
Request heatmap.news

### ISSUE THREAD

**Issue by enaloha** [bpc-clone/bpc_chrome_support#123]
Describe issue/request: 

This site appears to post a short version of the article and requires login to continue (I assume it creates a new URL?)

Link of paywalled article: https://heatmap.news/climate/what-is-carbon-removal

Browser (main version): Chrome Version 126.0.6478.127 (Official Build) (arm64)

BPC-extension version (number): 3.7.2.0

**Comment by bpc-clone** [comment]
Site just hides article with an overlay, but you can add these filters to your adblocker:\
heatmap.news##+js(ra, style, div.body-description, stay)  
heatmap.news##div.regwall-container

PS use full issue template (actions you tried yourself like reader view etc.).
