### ISSUE TITLE
Request capital.de

### ISSUE THREAD

**Issue by cpy82** [bpc-clone/bpc_chrome_support#125]
Link of paywalled article: https://www.capital.de/geld-versicherungen/ishares-automation---robotics-ucits-etf--rendite-mit-technologie--34819026.html

Actions you tried yourself: clear cookies, disabe Javascript, reader view, archive sites: none 

Browser (main version): Chrome 126.0.6478.127 (Official Build) (64-Bit)

BPC-extension version (number): 3.7.3.0

Thanks!

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
