### ISSUE TITLE
Request fipp.com

### ISSUE THREAD

**Issue by Vinh2091** [bpc-clone/bpc_chrome_support#130]
Dear BPC Team,
Can your team add new website?
Describe issue/request: All Reports on this site are about the scale of the Media Market.

Link of paywalled article: 
https://www.fipp.com/resource-type/reports/
https://www.fipp.com/resource/global-digital-subscription-snapshot-2023-q4/

Browser (main version): Edge

BPC-extension version (number): 3.7.3.1
Thank you so much!

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.\
PS next time use full issue template (actions you tried yourself).

**Comment by Vinh2091** [comment]
Thank you for reply to me!
