### ISSUE TITLE
request update for saltwire.com

### ISSUE THREAD

**Issue by bill-ns** [bpc-clone/bpc_chrome_support#132]
Describe issue/request: extension not working for saltwire.com

Link of paywalled article: https://www.saltwire.com/halifax/news/john-demont-andy-fillmore-ends-worst-kept-secret-in-the-hrm-announces-hes-running-for-mayor-100976922/

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): cleared cookies/disabled/enabled JS, disabled/enabled Adblock Plus

Browser (main version): Chrome 126.0.6478.127

BPC-extension version (number): v3.7.3.4

Thanks

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix) now, it seems: it will be removed from extension.

**Comment by bill-ns** [comment]
great, thanks anyway
