### ISSUE TITLE
Request lifeweek.com.cn

### ISSUE THREAD

**Issue by flypigJ** [bpc-clone/bpc_chrome_support#134]
Describe issue/request: 
**Request https://www.lifeweek.com.cn/**

Link of paywalled article: 
https://www.lifeweek.com.cn/article/229380

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
**Tried**:clear cookies, disabe Javascript, change user-agent/referer, reader view **no use**

Browser (main version): 
**MS edge 128.0.2677.1 (Official build) dev (64-bit)** 

BPC-extension version (number): 
**v3.7.3.0** 

PS always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
