### ISSUE TITLE
Request for jacobin.com

### ISSUE THREAD

**Issue by muktokhechor** [bpc-clone/bpc_chrome_support#135]
Describe issue/request: please add

Link of paywalled article: https://jacobin.com/2024/01/high-tech-desert-hellscape

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

Browser (main version): Chrome 120.0

BPC-extension version (number): v3.7.3.0

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
