### ISSUE TITLE
Request for solicitorsjournal.com

### ISSUE THREAD

**Issue by muktokhechor** [bpc-clone/bpc_chrome_support#139]
Describe issue/request: add site

Link of paywalled article: https://www.solicitorsjournal.com/sjarticle/supreme-court-rules-unanimously-against-home-secretary-in-landmark-libel-claim-brought-by-prominent-muslim-community-leader-chowdhury-mueenuddin

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

Browser (main version): Chrome 120.0

BPC-extension version (number): v3.7.3

**Comment by bpc-clone** [comment]
Always first try the actions in the issue template: disable Javascript will show full content.

Update: domain added to custom sites (import from online).

**Comment by muktokhechor** [comment]
Ok
