### ISSUE TITLE
Request Finanz-Szene.de

### ISSUE THREAD

**Issue by gummipunkt** [bpc-clone/bpc_chrome_support#141]
Link of paywalled article: https://finanz-szene.de/fintech/wie-trade-republic-und-scalable-capital-den-kompletten-markt-aufsaugen/

Actions you tried yourself (mandatory):
{"Finanz Szene":{"amp_unhide":1,"block_js":1,"block_js_ext":1,"block_regex_ignore_default":1,"domain":"finanz-szene.de","random_ip":"eu","referer":"google","remove_cookies":1,"useragent":"googlebot"}}

and if it works: Works  

Browser (main version): Chrome

BPC-extension version (number): v3.7.4.0

**Comment by bpc-clone** [comment]
Domain is already in custom sites (import from online); only Googlebot-fix is needed.
