### ISSUE TITLE
Request/bug energy-storage.news

### ISSUE THREAD

**Issue by benreads** [bpc-clone/bpc_chrome_support#142]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: Site behind soft payall, site not in the master list of sites

Link of paywalled article: https://www.energy-storage.news/bess-commoditising-industry-converges-20-foot-5mwh-products/

Actions you tried yourself (mandatory) and if it works (clear cookies, disabe javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Tried clearing/disabling javascript, and useragents/reading mode, and archive sites.

(Can see the content in HTML but not a whiz at figuring out how to stop certain elements loading etc)

Browser (main version): Chrome

BPC-extension version (number): Latest

**Comment by bpc-clone** [comment]
Site already part of group_uk_solar_media (opt-in to custom sites & import in custom sites).
