### ISSUE TITLE
Requesting access for VI.nl

### ISSUE THREAD

**Issue by ultrazeus** [bpc-clone/bpc_chrome_support#145]
**Describe issue/request**: requesting access for https://www.vi.nl, nr. 1 soccer news website in NL

**Link to paywalled article**: https://www.vi.nl/pro/analyse/zes-conclusies-na-nederland---engeland

**Actions tried, without success:**
1. cleared cookies
2. disabled javascript
3. changed user-agent/referer
4. reader view
5. archive sites

**Other:**
Browser: Brave; version 1.67.123 Chromium: 126.0.6478.126 (Official Build)
BPC-extension version: 3.7.4.0

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
