### ISSUE TITLE
augsburger-allgemeine.de no longer works

### ISSUE THREAD

**Issue by KarateKaenguru** [bpc-clone/bpc_chrome_support#146]
Describe issue/request: augsburger-allgemeine.de have recently changed their layout and paywall system, since then I can't access paywalled articles anymore

Link of paywalled article: https://www.augsburger-allgemeine.de/augsburg/augsburg-theatersanierung-streichung-des-kleinen-hauses-wuerde-nur-800-000-euro-bringen-102868362?

Actions you tried yourself (mandatory) and if it works (clear cookies, disabe javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

Browser (main version): Ungoogled Chromium Latest Build

BPC-extension version (number): Latest build

**Comment by bpc-clone** [comment]
Site fixed in latest master/update rules (or next release).

**Comment by KarateKaenguru** [comment]
Nice, thank you so much!

**Comment by KarateKaenguru** [comment]
The articles are working again, but photo-slideshows only show the first picture: https://www.augsburger-allgemeine.de/landsberg/bildergalerie-kaltenberger-gauklernacht-der-umzug-102873098
Is there any way to fix that?

**Comment by bpc-clone** [comment]
No fix, but you can try the `actions you tried yourself`

**Comment by KarateKaenguru** [comment]
I am an absolute noob, so I have no idea how to make those picture galleries work. Yes, I've read your instructions on github on how to add a custom site, but that doesn't help me in this case. I would really appreciate it if you could maybe help me out. When I click on the google search tool and then click on "tested site" and then on "screenshot", I can see all the pictures in a small frame.  If I copy that html code into a html viewer, then I can access all the pictues. But is there any way to make them display on the normal site? I would really appreciate it if you could help me out as I am lacking the required technical knowledge.

**Comment by bpc-clone** [comment]
Link to Google Search Tool added in next release, but no proper fix.\
PS next time always first try the do-it-yourself options you're familiar with (like archive-sites etc.).
