### ISSUE TITLE
Request: pcgameshardware.de

### ISSUE THREAD

**Issue by KarateKaenguru** [bpc-clone/bpc_chrome_support#148]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: Can't access paywalled articles

Link of paywalled article: https://www.pcgameshardware.de/Counter-Strike-2-Spiel-74230/Specials/Latenzverringerung-mit-Anti-Lag-2-in-Counter-Strike-2-1451085/

Actions you tried yourself (mandatory) and if it works (clear cookies, disabe javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

Browser (main version): Ungoogled Chromium Latest Build

BPC-extension version (number): Latest

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.\
PS always use full issue template: `Actions you tried yourself (mandatory)`
