### ISSUE TITLE
Request cfnews.net

### ISSUE THREAD

**Issue by itspgold** [bpc-clone/bpc_chrome_support#149]
Describe issue/request: Cfnews.net doesn't work

Link of paywalled article: https://www.cfnews.net/L-actualite/Build-up/Operations/Build-up-international/Steliau-poursuit-ses-emplettes-en-Italie-492678

I tried to clear cookies, disabe javascript, change user-agent/referer, reader view, archive sites and/or add a custom site

Browser (main version): Version 124.0.6367.119

BPC-extension version (number): Latest

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
