### ISSUE TITLE
dealstreetasia.com no longer works

### ISSUE THREAD

**Issue by FreddyBoy98** [bpc-clone/bpc_chrome_support#152]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: Hi - first, thanks for your great program! Was using it to read dealstreetasia articles, but now certain articles don't seem to work (for example, article below)

Link of paywalled article: https://www.dealstreetasia.com/stories/delistings-outnumber-ipos-in-hkex-404600

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): clear cookies, disable javascript, archive sites

Browser (main version): Edge

BPC-extension version (number): 3.7.5.4

**Comment by bpc-clone** [comment]
Page source no longer contains full article content (no fix): site will be removed from extension.
