### ISSUE TITLE
epaper.thehindu.com doesn't load properly

### ISSUE THREAD

**Issue by Achyuth072** [bpc-clone/bpc_chrome_support#156]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: TheHindu was mentioned in its supported sites, and this being its subsidiary was working very fine too but recently the epaper never stops loading, the only thing that it loads is the front page of the international edition, everything else keeps loading forever irrespective of whichever edition you choose.

Link of paywalled article: https://epaper.thehindu.com/reader

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): clear cookies, archive sites

Browser (main version): Kiwi 124.0.6327.4, Vivaldi 6.8.3381.48

BPC-extension version (number): v3.7.5.0

**Comment by bpc-clone** [comment]
No fix: exception added for epaper subdomain (BPC icon will show ON-).
