### ISSUE TITLE
Request intelligenceonline.com

### ISSUE THREAD

**Issue by Headhunter2024** [bpc-clone/bpc_chrome_support#160]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: bypassing paywall

Link of paywalled article: https://www.intelligenceonline.com/government-intelligence/2024/07/19/the-baku-and-tbilisi-spymaster-connections-of-london-cafe-catalyst,110269971-eve

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): all archive webpages, waybackmachine, cleared cookies, installed bypass paywal. 

Browser (main version): chrome

BPC-extension version (number): Bypass Paywalls Clean v3.7.6.2

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)
