### ISSUE TITLE
Request sydsvenskan.se

### ISSUE THREAD

**Issue by dviree** [bpc-clone/bpc_chrome_support#163]
Describe issue/request: 
Paywall

Link of paywalled article: 
https://www.sydsvenskan.se/2024-07-27/foretradare-for-sondagsdemonstrationerna-man-jagar-inte-journalister-som-gor-sitt-jobb/
Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
All of the above
Browser (main version): 
Firefox
BPC-extension version (number): 
Latest [3.7.6.0]

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
