### ISSUE TITLE
Bug Haaretz.co.il / themarker.com

### ISSUE THREAD

**Issue by ido1901** [bpc-clone/bpc_chrome_support#172]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: Initially the bypass works just fine. After a few minutes, the website will "refresh", and go to an error page: 
![image](https://github.com/user-attachments/assets/9c4a2d55-6b93-42c5-b509-4438d88ed9d6)
this happens in all paid articled on both websites. No action by the user is causing this, it just happens.

Link of paywalled article: [as an example](https://www.haaretz.co.il/sport/olympics/2024-08-03/ty-article/00000191-12de-df57-afd7-f2fe753a0000), but it happens with any.

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): yes, when in reader view I can keep reading. When closing reader view the same error is shown (so it still happens in the background, just that the browser's reader view doesn't update that thankfully)

Browser (main version): Edge 127 (Windows & Android), Firefox 128 (Windows & Android)

PC-extension version (number): 3.7.7.5

This has been happening of a while now, I believe it's more of a change by the website and not the extension. Maybe it's possible to block this "refresh" action so it won't show the error?

**Comment by bpc-clone** [comment]
Group fixed in latest master/update rules (or next release): both error & videos.
