### ISSUE TITLE
Request btc-echo.de

### ISSUE THREAD

**Issue by cpy82** [bpc-clone/bpc_chrome_support#175]
**Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).** -> done
**Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).** -> done

Describe request: 

Link of paywalled article: https://www.btc-echo.de/news/bitcoin-korrektur-wie-stark-anleger-von-flash-crashes-profitierten-189476/

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
clear cookies: does not work
disable javascript: does not work
reader view: does not work
archive sites: does not work

Browser (main version): Chrome 127.0.6533.89 (Offizieller Build) (64-Bit)

BPC-extension version (number): v3.7.8.0

Thank you!

**Comment by bpc-clone** [comment]
Domain is part of custom sites (opt-in to custom sites & import from online).
