### ISSUE TITLE
Request opensnow.com

### ISSUE THREAD

**Issue by KScheid** [bpc-clone/bpc_chrome_support#176]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix). > done

Describe issue/request: Unable to remove paywall

Link of paywalled article: https://opensnow.com/dailysnow/utah

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site):  clear cookies, disable javascript, change user agent, reader view

Browser (main version): Chrome Version 126.0.6478.222 (Official Build) (64-bit)

BPC-extension version (number): v3.7.8.2

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
