### ISSUE TITLE
Request [bisnis.com]

### ISSUE THREAD

**Issue by 3xploiton3** [bpc-clone/bpc_chrome_support#177]
https://market.bisnis.com/read/20240808/192/1789057/prospek-cuan-emiten-ritel-aces-eraa-midi-cs-usai-kinerja-paruh-tahun-moncer

![image](https://github.com/user-attachments/assets/f7aef42d-305f-42be-8007-3eaf563d2742)

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
