### ISSUE TITLE
New Request xakep.ru

### ISSUE THREAD

**Issue by fashionking1818** [bpc-clone/bpc_chrome_support#18]
Describe issue/request: Hope a new site [https://xakep.ru](https://xakep.ru) could be added

Link of paywalled article: [https://xakep.ru/2024/02/01/cs-spyware/](https://xakep.ru/2024/02/01/cs-spyware/)

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

clear cookies: Not work
disabe Javascript: Not work
change user-agent: Not work (only changed to android, maybe others work?)
reader view: Chrome reading mode not work
archive sites: not work

Browser (main version): Chrome Version 124.0.6367.63 (Official Build) (64-bit)

BPC-extension version (number): 

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
