### ISSUE TITLE
Request [publico.pt]

### ISSUE THREAD

**Issue by jp99esas19** [bpc-clone/bpc_chrome_support#181]
Describe issue/request: Can't access paywalled articles

Link of paywalled article: https://www.publico.pt/2024/08/08/p3/noticia/ministerio-publico-vai-abrir-inquerito-investigar-morte-lince-bores-madeira-2100284

I've tried clearing cookies, disabing javascript, using archive.is, google cache, reader viewer, added to custom sites, all to no avail

Browser (main version): Chrome v.127.0.6533.100 

BPC-extension version (number): v3.7.8.5

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)

**Comment by jp99esas19** [comment]
Thank you for the reply, great work on the extension, life saver
