### ISSUE TITLE
Request [ojogo.pt]

### ISSUE THREAD

**Issue by jp99esas19** [bpc-clone/bpc_chrome_support#182]
Describe issue/request: Can't access paywalled articles

Link of paywalled article: https://www.ojogo.pt/4547984774/alexandrina-cruz-houve-meses-em-que-vivemos-uma-angustia-terrivel/

I've tried clearing cookies, disabing javascript, using archive.is, google cache, reader viewer, added to custom sites, all to no avail

Browser (main version): Chrome v.127.0.6533.100 

BPC-extension version (number): v3.7.8.5

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.

**Comment by jp99esas19** [comment]
Thank you for the reply
