### ISSUE TITLE
Request/bug today.lorientlejour.com

### ISSUE THREAD

**Issue by will197** [bpc-clone/bpc_chrome_support#183]
Describe issue/request: Add to Default Sites: today.lorientlejour.com

Link of paywalled article: https://today.lorientlejour.com/article/1423401/cyprus-insists-not-involved-in-any-conflict-as-uss-wasp-passes-through-limassol.html

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): It works fine by doing: clear cookies and disable javascript

Browser (main version): Chrome 127.0.6533.100 

BPC-extension version (number): v3.7.8.7

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.\
PS your 'fix' isn't working for me though.
