### ISSUE TITLE
cn.wsj.com not working anymore

### ISSUE THREAD

**Issue by zer0xOO** [bpc-clone/bpc_chrome_support#186]
The versions 3.7.8.0 and 3.7.9.0 are not working for cn.wsj.com, can you fix it? I tested on web Chrome and Android Kiwi browser/Firefox, it is stuck when entering the news detail page.

**Comment by pupumao** [comment]
+1

**Comment by bpc-clone** [comment]
No fix: cn subdomain is no longer supported.\
PS always use issue template.

**Comment by MylQl** [comment]
> The versions 3.7.8.0 and 3.7.9.0 are not working for cn.wsj.com, can you fix it? I tested on web Chrome and Android Kiwi browser/Firefox, it is stuck when entering the news detail page.

你可以打开wsj的英文官网，选择China栏目，内容和cn.wsj.com一模一样，选择你想看的文章后右键Google翻译成简体。

**Comment by gsragcgdfhk** [comment]
> > The versions 3.7.8.0 and 3.7.9.0 are not working for cn.wsj.com, can you fix it? I tested on web Chrome and Android Kiwi browser/Firefox, it is stuck when entering the news detail page.
> 
> 你可以打开wsj的英文官网，选择China栏目，内容和cn.wsj.com一模一样，选择你想看的文章后右键Google翻译成简体。

thanks!

**Comment by zer0xOO** [comment]
> > The versions 3.7.8.0 and 3.7.9.0 are not working for cn.wsj.com, can you fix it? I tested on web Chrome and Android Kiwi browser/Firefox, it is stuck when entering the news detail page.
> 
> 你可以打开wsj的英文官网，选择China栏目，内容和cn.wsj.com一模一样，选择你想看的文章后右键Google翻译成简体。

Thank u, but I think some articles delayed update

**Comment by kangaroo711** [comment]
so sad

**Comment by luke-zhang-wcar** [comment]
去掉url里面的cn就可以正常浏览了

**Comment by bpc-clone** [comment]
> 去掉url里面的cn就可以正常浏览了 = Remove the cn in the url and you can browse normally

Indeed, I'll add a redirect from cn to www subdomain later today.

Update: site fixed in latest master (or next release).
