### ISSUE TITLE
Request onvista.de

### ISSUE THREAD

**Issue by cpy82** [bpc-clone/bpc_chrome_support#187]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version) -> done
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix). -> done

Describe request: 

Link of paywalled article: https://www.onvista.de/news/2024/08-04-kolumne-von-stefan-risse-04-08-2024-schatten-ueber-den-finanzmaerkten-41095284-24-26298088

Actions you tried yourself (mandatory) and if it works:
clear cookies: don't work 
disable javascript: don't work
reader view: don't work
archive sites: dont' work

Browser (main version): Chrome 127.0.6533.100 (Offizieller Build) (64-Bit)

BPC-extension version (number): 3.7.9.0

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
