### ISSUE TITLE
Request sspai.com

### ISSUE THREAD

**Issue by flypigJ** [bpc-clone/bpc_chrome_support#188]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: custom rules not working on sspai.com 

Link of paywalled article: 
https://sspai.com/prime/story/inside-release-notes-240806
https://sspai.com/post/90732
**Maybe the second link has hard paywalls**

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): **clear cookies, disable javascript, change user-agent/referer,archive sites and/or add a custom site**,no use

Browser (main version): edge latest stable

BPC-extension version (number): 3.7.90

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
