### ISSUE TITLE
Please host gitflic.ru download file hashes on github.com

### ISSUE THREAD

**Issue by timkgh** [bpc-clone/bpc_chrome_support#191]
Now that updates have moved to gitflic.ru, please make release file hashes (sha256) available for download from a different site, e.g. github.com, so that we can verify what we download from gitflic.ru hasn't been tampered with. Thank you.

**Comment by YesTrustMe** [comment]
I totally agree. I've never seen so many extensions 'tampered' on Github before like has been the case recently. Even the file names are incomplete on the Russian site.

**Comment by bpc-clone** [comment]
> Now that updates have moved to gitflic.ru, please make release file hashes (sha256) available for download from a different site, e.g. github.com, so that we can verify what we download from gitflic.ru hasn't been tampered with. Thank you.

No problem to add release-hashes, but who is going to tamper with the files GitlFlic or the 'Russians' ...?

**Comment by timkgh** [comment]
> No problem to add release-hashes, but who is going to tamper with the files GitlFlic or the 'Russians' ...?

yes

**Comment by bpc-clone** [comment]
Release-hashes added to the GitHub repos.

**Comment by cspence001** [comment]
I've created [this python script](https://gist.github.com/cspence001/33302cf180212a22423e4abcd2aa7868) that checks the gitflic zip-file hash against the provided release-hashes on github. If the hashes match and the user confirms, it extracts the contents and updates the Chrome extension (if it was installed using "Load Unpacked" in Developer Mode).

Here's [another](https://gist.github.com/cspence001/0bd115d54ff5cb3d1b28752b349d51f7) that just verifies the hash.

**Comment by bpc-clone** [comment]
> I've created [this python script](https://gist.github.com/cspence001/33302cf180212a22423e4abcd2aa7868) that checks the gitflic zip-file hash against the provided release-hashes on github. If the hashes match and the user confirms, it extracts the contents and updates the Chrome extension (if it was installed using "Load Unpacked" in Developer Mode).

Very usefull script for users to keep up with the updates ;-)
