### ISSUE TITLE
Site no longer works [record.pt]

### ISSUE THREAD

**Issue by jp99esas19** [bpc-clone/bpc_chrome_support#192]
Describe issue/request: record.pt no longer works

Link of paywalled article: https://www.record.pt/futebol/futebol-nacional/liga-betclic/benfica/detalhe/arthur-mais-longe-do-brentford

Tried updating the extension, it worked OK yesterday

Browser (main version): 127.0.6533.101 

BPC-extension version (number): v3.7.9.0

**Comment by bpc-clone** [comment]
Site fixed in latest master (or next release).
