### ISSUE TITLE
Request [onetz.de/]

### ISSUE THREAD

**Issue by vivandi001** [bpc-clone/bpc_chrome_support#196]
Describe issue/request: 

Link of paywalled article:  https://www.onetz.de/oberpfalz/nabburg/bens-heikler-auftrag-oberpfaelzer-soldat-spricht-ueber-einsaetze-afghanistan-id4893897.html

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): clear cookies, disable javascript, change user-agent, reader view, add a custom site

Browser (main version): Brave Version 1.68.141 Chromium: 127.0.6533.120 

BPC-extension version (number):  Bypass Paywalls Clean 3.7.9.4

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.\
Full text is available in Google Search Tool (see BPC icon) though, but very elaborate 'fix'.
