### ISSUE TITLE
Request to add the-ken.com

### ISSUE THREAD

**Issue by rakesh-it** [bpc-clone/bpc_chrome_support#198]
I would like to request bpc-clone team to add "the-ken.com" domain to the list of sites.

Link of paywalled article: https://the-ken.com/story/what-does-awfis-know-about-co-working-that-wework-doesnt/

Actions tried :  Cleared Cookies, js-disable, referrer changed- no luck, reader view doesn't work, unavailable in archived sites.

Browser (main version): 127.0.2651.105 (Official build) (arm64)

BPC-extension version (number): 3.7.9.6

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)
