### ISSUE TITLE
Request ziplaw.uk

### ISSUE THREAD

**Issue by username1745** [bpc-clone/bpc_chrome_support#199]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: please add the site www.ziplaw.uk/

Link of paywalled article: https://www.ziplaw.uk/ 
https://www.ziplaw.uk/ziptracker-issue-1/  

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): **clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site** - tried all, didn't work

Browser (main version): Chrome

BPC-extension version (number): 3.7.9.6

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)
