### ISSUE TITLE
Request/bug [richmondbizsense.com]

### ISSUE THREAD

**Issue by MVECoder** [bpc-clone/bpc_chrome_support#201]
Describe issue/request: "Pro" access.  Likely hard paywall.

Link of paywalled article:  https://richmondbizsense.com/2024/08/16/the-deedbook-local-property-transfers-for-8-16-24/

Browser (main version):  127.0.6533.120

BPC-extension version (number):   3.8.0.0

**Comment by bpc-clone** [comment]
Add these filters to your adblocker (site just hides content):\
richmondbizsense.com##+js(ra, class, div.cp-paywall-user)\
richmondbizsense.com##div#copperpress-paywall

PS next time first use the do-it-yourself options (mandatory) like reader mode (has full content).
