### ISSUE TITLE
Haaretz group no longer works

### ISSUE THREAD

**Issue by ido1901** [bpc-clone/bpc_chrome_support#203]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: I get this error with any haaretz.co.il or themarker.com link, including the homepage.
![image](https://github.com/user-attachments/assets/3d91a597-926d-4405-aa74-8bb18a370342)

They do this from time to time, you usually find a fix. I hope you'll be able to fix it again! :) Very appreciated 

Link of paywalled article: https://www.haaretz.co.il/

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): archive sites work, but the bot fix is miles better. Websites work fine with the extension disabled.

Browser (main version): Edge 127 (Win & Android), Firefox 129 (Win & Android)

BPC-extension version (number): 3.8.0.0 (Edge) & 3.7.9.0 (FF)

**Comment by pedroan02** [comment]
We all hope that there will be an update :)

**Comment by mekler22** [comment]
Add: Same happens with themarker.com as they're both using the same systems.

**Comment by tomkoi** [comment]
@bpc-clone oh no, in latest master it looks better BUT NOT unlocked the article :(

**Comment by tomkoi** [comment]
@ido1901  at least the HMTL is working (the unlock)

**Comment by Guevald** [comment]
@ido1901 @tomkoi did you manage to get it to work at all with a workaround? firefox? toda!

**Comment by tomkoi** [comment]
> @ido1901 @tomkoi did you manage to get it to work at all with a workaround? firefox? toda!

i tried just to use with HTML option but of course it's not good as the add-on doing without any 3rd party tool

**Comment by Guevald** [comment]
what is HTML option?

**Comment by Ilantatar** [comment]
Waiting for [Haaretz.co.il](https://www.haaretz.co.il/) fix, Thanks

**Comment by naveh-yo** [comment]
Waiting for a fix. Thanks!

**Comment by bpc-clone** [comment]
Site fixed in latest master/update rules (or next release).\
If update rules doesn't fix the issue: disable group in options & open article with archive.today (see BPC icon).

**Comment by tomkoi** [comment]
> Site fixed in latest master/update rules (or next release). If update rules doesn't fix the issue: disable group in options & open article with archive.today (see BPC icon).

you are the best!
thank you!

**Comment by Galgul1** [comment]
Thank you!

I now mostly get "BPC > Try for full article text (no need to report issue for external site) | no article content found!".
Should we expect a better solution or is that it?

Thank you!

**Comment by tomkoi** [comment]
> @Galgul1 url and extension version?

for example:
https://www.themarker.com/advertising/2024-08-25/ty-article/.premium/00000191-893a-d8c0-abff-9bfef1ec0000
latest master - 3.8.0.8

**Comment by Galgul1** [comment]
3.8.1.1
Kiwi on Android 
https://www.haaretz.co.il/news/politics/2024-08-25/ty-article/.highlight/00000191-85de-d632-add9-b5ff249f0000

Shows sone desktop version of the article which is not mobile friendly

**Comment by eliuha** [comment]
does not work for me on version 3.8.1.1

**Comment by mekler22** [comment]
> does not work for me on version 3.8.1.1

works fine. but you need to wait a minute or two as the page actually re-loads

**Comment by Galgul1** [comment]
> You can complain to archive.is for not having a mobile version though.

Did something fundamentally changed in the last release? 

In the past, haaretz group sites looked great on mobile and there were no reload delays. Is the current bpc solution different than the one used previously?

**Comment by Ilantatar** [comment]
Installed version 3.8.1.1 on Chrome, it works for me, but in a different way than it was fixed previously. now the articles are being opened after a while using BCP  (Haaretz& theMarker

**Comment by mderazon** [comment]
Was anyone here able to bypass their anti-adblocker ?

**Comment by mekler22** [comment]
> Was anyone here able to bypass their anti-adblocker ?

Yes. It works, but you have to wait maybe upto a minute for the full article to load.

**Comment by bpc-clone** [comment]
> Was anyone here able to bypass their anti-adblocker ?

@mderazon Better file an issue with adblocker filters like EasyList, but they don't have a working fix though.

A crude fix is to block the webpack-script (add to your adblocker), but this will also block a lot of other features:\
`/v2/*-bucket/_next/static/chunks/webpack-*.js$script,~third-party,domain=haaretz.com|haaretz.co.il|themarker.com`

**Comment by mderazon** [comment]
> A crude fix is to block the webpack-script

Once adblock is detected, it is redirecting to `haaretz.co.il/hblocked` perhaps that redirection can be blocked from happening and user will just stay on the page
