### ISSUE TITLE
Marketwatch no longer works

### ISSUE THREAD

**Issue by chrisc0** [bpc-clone/bpc_chrome_support#21]
Describe issue/request: 
Marketwatch no longer works

Link of paywalled article: 
https://www.marketwatch.com/story/the-10-most-expensive-cars-to-maintain-a898394c

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

Browser (main version): 
Brave

BPC-extension version (number): 
3.6.6.2

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site fixed in latest master (or next release).
