### ISSUE TITLE
Request taxinstitute.com.au

### ISSUE THREAD

**Issue by Ngalyod** [bpc-clone/bpc_chrome_support#210]
Describe request: blocking JavaScript let’s me access articles like https://archive.is/https://www.taxinstitute.com.au/insights/articles/deducting-car---travel-expenses but I cannot download files as the subscriber tab opens. I can locate with some certainty the JavaScript and CSS files associated with the softwalls but I don’t know how to integrate them with the extension?

Link of paywalled article: https://www.taxinstitute.com.au/tke/all-events/2018/march/33rd-national-convention/deductibility-of-employee-travel-expenses-the-ato-s-guidance/deductibility-of-employee-travel-expenses-the-ato-s-guidance-paper#

Actions you tried yourself: disabled JavaScript (both domain and ext, by themselves and both), changed use-agent. Archive.today’s list of saved articles indicates they are all unsuccessful attempts. Articles can be viewed by JavaScript blocking, downloadable files are in not accessible. 

Browser (main version): latest Chrome

BPC-extension version (number): 3.8.0.4

**Comment by bpc-clone** [comment]
Site just hides content with a blur-overlay (no fix for downloads).\
First add these filters to your adblocker:\
taxinstitute.com.au##+js(ra, style, div.main-container, stay)  
taxinstitute.com.au##div.memberpopup

PS only paywall for old articles?
