### ISSUE TITLE
No comment on dailytelegraph.com.au (dev: all AU News Corp)

### ISSUE THREAD

**Issue by AnthonyLeKoala** [bpc-clone/bpc_chrome_support#214]
**reader's comments not seen on Daily Telegraph.**
When you go to the main page of The Daily Telegraph, there are a number of aricles. 

When you see at the bottom left hand corner of the headlined article, you will see a number indicating the number of reader's comments.

Take for example this aricle headline "Another Veteran Journalist Leaves Seven"

![Screenshot_20240825-122505](https://github.com/user-attachments/assets/7a37a691-8822-4627-85a5-3acbcaa8d5f2)

At the bottom left you see the number 12 to the right of a square box.

Click on the article there is no information at the top of the article nor at the bottom of the article reader's comments:

At the top of the article you should see "12 comments" which is supposed to hyperlink you to the bottom of the article: but it is not there

![Screenshot_20240825-123013](https://github.com/user-attachments/assets/40193376-68fe-4f7f-bd28-42a45a4ca61a)

At the bottom of the article you are supposed see "join the conversation" and/or "12 comments" of which you you should see the 12 comments:

![Screenshot_20240825-123024](https://github.com/user-attachments/assets/13b28d83-99ed-47de-9082-5c116bbb02ac)

The article is at 
https://www.dailytelegraph.com.au/entertainment/sydney-confidential/is-it-an-age-thing-or-a-wage-thing-another-7-veteran-leaves-the-network/news-story/57ca9cf4ed6ed00fe5ac0fe91e21f444?amp

The headlined article with the number of comments may have changed by the time you atteneded as at 1237, is here:
https://www.dailytelegraph.com.au.
The contents may have changed. Please refer to first screenshot

**Conclusion**
Comments cannot be seen despite the headline to the article showing that there were supposed to be comments.

This is not the only article in the Daily Telegraph. All articles with headlines indicating readers comments, when you click the article shows no reader's comment.

Thanks

**Comment by bpc-clone** [comment]
No fix, but indeed no comments on amp-pages.

**Comment by GeorgeCastanza** [comment]
@AnthonyLeKoala how are you getting News Corp articles at all.  My BPC has not been working for 2 weeks or so?

Can you share your setup?

**Comment by AnthonyLeKoala** [comment]
**Reader's comments are there**
The moderator bpc-clone  was correct in that there were no comments for that article.

It was unusual for that particular issue as there were no reader's comments for **any** article.

Reader's comments appear on selected articles.

**What is my setup?**
* Android v13
* Kiwi Browser >= v124.
* bpc should automatically install updates once it is installed.
* how to install/update the addin?
   **Follow** the instructions on the home page of this github addin
   * look at your machine: is it a tablet? a pc? an android phone?
   *  follow the instructions by scrolling down the home page of this github page.

Thanks
