### ISSUE TITLE
Request: cphpost.dk

### ISSUE THREAD

**Issue by guydvd** [bpc-clone/bpc_chrome_support#220]
Thank you very much for your wonderful 'Add on'
Would it be possible to add this website from Denmark to your list
I have tried other methods including what is described here.
Here is an article for example
https://cphpost.dk/2024-08-27/news/business/novo-nordisk-director-defends-wegovy-prices-on-us-tv-amid-fresh-criticism/
Guy

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.\
PS always use issue template.
