### ISSUE TITLE
Request: al-monitor.com

### ISSUE THREAD

**Issue by thesearcher223** [bpc-clone/bpc_chrome_support#225]
Link of paywalled article: [al-monitor.com](https://www.al-monitor.com/)\
paywall shows after 4 articles read

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): i have tried customs options also cleaned cookies but didnt work

Browser (main version): chrome

BPC-extension version (number): 3.8.1.4

Hi, i like your extension a lot and has helped me read through articles without having to pay, im sending this request to ask if you could kindly add https://www.al-monitor.com/ to the list. It's a website that shares news about the middle east and would help me a lot being a student!

**Comment by thesearcher223** [comment]
Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): i have tried customs options also cleaned cookies but didnt work

Browser (main version): chrome

BPC version: 3.8.1.4

**Comment by thesearcher223** [comment]
sorry, they're not.

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
