### ISSUE TITLE
Request sumzero.com

### ISSUE THREAD

**Issue by Marco14269** [bpc-clone/bpc_chrome_support#227]
Describe issue/request: hi i cant get through this site hard paywall

Link of paywalled article: https://sumzero.com/public/ideas/22543

Actions you tried yourself (mandatory) ive tried disabling javascript,using ft12,archive.ph and some chrome extensions but they dont work.

Browser (main version): chrome

BPC-extension version (number): v3.8.1.6

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
