### ISSUE TITLE
SCMP.com no longer working

### ISSUE THREAD

**Issue by kennethtang12345** [bpc-clone/bpc_chrome_support#231]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: **I think two days ago I could read full articles on https://www.scmp.com/ . But today i found out that it has been blocked.**

Link of paywalled article: **this is one of the sample**
https://www.scmp.com/economy/china-economy/article/3276871/chinas-railway-operator-brings-gravy-train-posting-profits-and-lowering-debt-ratios?module=top_story&pgtype=homepage 

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): **I already try your suggestion write on Github but not works.**

Browser (main version): **firefox and Chrome**

BPC-extension version (number): **v3.8.2.1**

**Comment by bpc-clone** [comment]
Site fixed in latest master (or next release).
