### ISSUE TITLE
Request: dnevnik.bg

### ISSUE THREAD

**Issue by yyuss** [bpc-clone/bpc_chrome_support#232]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: Since few days some of the articles of dnevnik.bg are behind paywall

Link of paywalled article: 
https://www.dnevnik.bg/bulgaria/2024/09/03/4668974_zashto_ne_se_razbraha_vuprosi_i_oslushvane_v_rodopite/?ref=home_mainStory 
Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

Browser (main version): 
Brave
BPC-extension version (number): v3.8.2.1

**Comment by bpc-clone** [comment]
Full text is included in the page source.\
I'll look for a fix later.

PS paywall is still worked on (БЕТА-ВЕРСИЯ = beta version)?

**Comment by yyuss** [comment]
Yes, it seems they are implementing it at the moment and are in beta version. Here is another example from this morning
https://www.dnevnik.bg/sviat/2024/09/04/4669204_kamala_haris_povdiga_zavesata_za_vunshnata_si_politika/?ref=home_mainStory

**Comment by bpc-clone** [comment]
Site fixed in latest master (or next release).

**Comment by yyuss** [comment]
Thanks a lot!
