### ISSUE TITLE
Request manager-magazin.de

### ISSUE THREAD

**Issue by lorentzkraft** [bpc-clone/bpc_chrome_support#235]
Describe issue/request: Add website https://www.manager-magazin.de

Link of paywalled article: https://www.manager-magazin.de/unternehmen/you-com-nvidia-salesforce-und-softbank-setzen-auf-diesen-deutschen-gruender-a-830367b2-19a0-490f-9c99-d82202e4362a

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site):

- Cookies cleared, Javascript disabled, tried to add custom site but failed... Tried to look into the source code but I wasn't successful

Browser (main version): Version 128.0.6613.84 (Official Build, ungoogled-chromium)

BPC-extension version (number): * v3.8.2.1 (2024-09-01)

**Comment by bpc-clone** [comment]
Site fixed in latest master/update rules (or next release).

**Comment by lorentzkraft** [comment]
Thank you so much!
