### ISSUE TITLE
Request: asahi.com

### ISSUE THREAD

**Issue by BrokenMirror-HNR** [bpc-clone/bpc_chrome_support#236]
Describe issue/request: add the site www.asahi.com

Link of paywalled article: https://www.asahi.com/articles/ASS932521S93ULFA012M.html?iref=comtop_7_07

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): clear cookies, reading mode

Browser (main version): Chrome v128.0.6613.119

BPC-extension version (number): v3.8.2.2

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)
