### ISSUE TITLE
Request: every.to

### ISSUE THREAD

**Issue by riogunawancom** [bpc-clone/bpc_chrome_support#237]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: New site requests

Link of paywalled article: https://every.to/also-true-for-humans/the-key-to-great-ai-prompting-show-don-t-tell

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Yap, blank page.

Browser (main version): Edge Version 128.0.2739.63

BPC-extension version (number): 3.8.2.1

**Comment by bpc-clone** [comment]
Try to add these filters to your adblocker:\
`/\/every\.to\/[-\w]+\//$inline-script`
`every.to##+js(ra, style, div#post-body-full, stay)`
