### ISSUE TITLE
Request handelsblatt.com

### ISSUE THREAD

**Issue by lorentzkraft** [bpc-clone/bpc_chrome_support#240]
Describe issue/request: Paywall cannot be deactivated.

Link of paywalled article: https://www.handelsblatt.com/unternehmen/industrie/interview-mit-oliver-blume-wir-muessen-volkswagen-robuster-aufstellen/100065696.html

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site):  Cookies cleared, javascript disabled, archives not working

Browser (main version): Version 128.0.6613.84 (Official Build, ungoogled-chromium)

BPC-extension version (number): * v3.8.3.0 (2024-09-08)

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
