### ISSUE TITLE
Request/bug [ftchinese.com, cn.wsj.com]

### ISSUE THREAD

**Issue by Qifull** [bpc-clone/bpc_chrome_support#241]
Describe issue/request:
Bypass Paywalls Chrome Clean v3.8.2.1 is unable to bypass the paywalls on the following websites:

	1.	https://www.ftchinese.com/
	2.	https://cn.wsj.com/

Link of paywalled article:

	•	Financial Times (Chinese): https://www.ftchinese.com/premium/001104158?exclusive
	•	Wall Street Journal (Chinese): https://cn.wsj.com/articles/%E7%A0%94%E7%A9%B6%E4%B8%AD%E5%9B%BD%E5%AF%B9%E4%BA%8E%E8%A5%BF%E6%96%B9%E5%AD%A6%E8%80%85%E6%9D%A5%E8%AF%B4%E6%84%88%E5%8F%91%E8%89%B0%E9%9A%BE-476bd1a7

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site):

	•	Cleared cookies (no fix)
	•	Disabled JavaScript (no fix)
	•	Changed user-agent/referer (no fix)
	•	Tested on other archive sites (no fix)

Browser (main version):

	•	Chrome version 128.0.6613.120 (Official Build) (arm64) macOS Sonoma
	•	Also reproduced on Windows 11

**Comment by bpc-clone** [comment]
Both (sub)domains aren't supported (no fix).
