### ISSUE TITLE
Request: thecipherbrief.com

### ISSUE THREAD

**Issue by fredgolightly** [bpc-clone/bpc_chrome_support#247]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: theciperbrief support

Link of paywalled article: https://www.thecipherbrief.com/cipher-brief-experts-offer-reflections-on-9-11-and-what-came-after

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): all the above, nothing works

Browser (main version): Kiwi, firefox android

BPC-extension version (number): 3.8.3.0

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
