### ISSUE TITLE
Fix nw.de (NW+ paywall content), please.

### ISSUE THREAD

**Issue by RivIdea** [bpc-clone/bpc_chrome_support#248]
Hi!

Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: The paywalled articles could be read till three days ago, the Google Search Tool fetches the raw paywalled content, still.

Link of paywalled article: https://www.nw.de/lokal/kreis_guetersloh/werther/23916003_Kein-Meistertitel-Cafe-im-Kreis-Guetersloh-darf-keine-Torten-mehr-To-Go-verkaufen-v1.html

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Tried all of them, nothing seemed to work but the Google Search Tool could still reliably display the raw paywalled content.

Browser (main version): Version 123.0.6312.56 (Official Build, ungoogled-chromium) (64-Bit)

BPC-extension version (number): 3.8.3.3

Thank you for your work.

**Comment by bpc-clone** [comment]
Site fixed (text-only) in latest master (or next release).
