### ISSUE TITLE
Request: bbwc.cn

### ISSUE THREAD

**Issue by iewall** [bpc-clone/bpc_chrome_support#251]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: add new site m.bbwc.cn

Link of paywalled article: 

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

Browser (main version): kiwi

BPC-extension version (number): 3.8.3.0

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
