### ISSUE TITLE
Request Reforma

### ISSUE THREAD

**Issue by dafle21** [bpc-clone/bpc_chrome_support#253]
I would like the following newspaper to be added to the list of supported websites:

https://www.reforma.com/

It is a renowned Mexican newspaper. Here is a sample paywalled article:

https://www.reforma.com/que-hacer-con-venezuela-2024-08-08/op276120

I have already cleared the cookies and I also tried reading via the usual tools (Archive.today, Google webcache, Clearthis.page). 

I used Google Chrome 128.0.6613.120 and BPC v3.3.4.3.

Thank you for your attention.

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
