### ISSUE TITLE
Request [ilmanifesto.it]

### ISSUE THREAD

**Issue by Lawrence-wq291** [bpc-clone/bpc_chrome_support#257]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: ilmanifesto.it articles are showing a paywall, but only at times.

Link of paywalled article: https://ilmanifesto.it/la-bce-da-un-timido-taglio-ai-tassi-dinteresse-la-crescita-continua-a-soffocare

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

- Clear Cookies
- Opt-In all 3 options
- Updated site rules and extension
- Enable/disable ublock Origin
- Searched in archive: https://search.google.com/test/rich-results/result?id=J7YjD_d7-gVTGL2CrQ7mUw

Browser (main version): Version 128.0.6613.138 (Official Build) (64-bit)

BPC-extension version (number): v 3.8.3.7

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
