### ISSUE TITLE
Request ChefSteps

### ISSUE THREAD

**Issue by TwitlerHimself** [bpc-clone/bpc_chrome_support#259]
**Describe issue/request:**
It would be great to get the content from www.chefsteps.com that is behind a paywall called "Studio Pass" since the company Breville bought that website.

**Link of paywalled article:** 
https://www.chefsteps.com/gallery?generator=chefsteps&published_status=published&difficulty=any&sort=newest&premium=Only%20Studio

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site):
I am too stupid for this, can't get it done.

Browser (main version): Google Chrome 128.0.6613.138

BPC-extension version (number): 3.8.4.1

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
