### ISSUE TITLE
Request: ifre.com

### ISSUE THREAD

**Issue by xZ9v** [bpc-clone/bpc_chrome_support#26]
Describe issue/request: if possible, it would be great to add the financial website below in the extension

Links for the paywalled articles: 
IFR
https://www.ifre.com/story/4553427/buzz-where-dollar-closes-at-the-end-of-the-week-is-key-for-direction-l1n3h50qu

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
 I tried to use some of the customs settings in the json file for other websites, but I didn't manage to get it working (the paywall splash screen was still blocking the content)

Browser (main version): Chromium on Linux

BPC-extension version (number):  Bypass Paywalls Clean v3.6.6.4  

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Request only one site per issue (for 2nd site open additional issue).

**Comment by xZ9v** [comment]
apologies, I didn't realize. I will create a second issue and rename the current one
thank you for this extremely useful tool

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
