### ISSUE TITLE
wiwo.de no longer working

### ISSUE THREAD

**Issue by BrokenMirror-HNR** [bpc-clone/bpc_chrome_support#265]
Describe issue/request: wiwo.de no longer works

Link of paywalled article: https://www.wiwo.de/my/politik/deutschland/baustopp-bei-intel-waechst-hier-in-zukunft-wirklich-noch-was/29997972.html

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): clear cookies; look direct into archive site

Browser (main version): chrome newest

BPC-extension version (number): v3.8.4.3

**Comment by bpc-clone** [comment]
Archive-fix site: `no need to report issue for external site`
