### ISSUE TITLE
[Bug regression] economist.com daily briefing no longer working

### ISSUE THREAD

**Issue by kranix0** [bpc-clone/bpc_chrome_support#27]
Describe issue/request: The paywall for The Economist daily briefing no longer works. Regular articles seem to be OK.

Link of paywalled article: https://www.economist.com/the-world-in-brief

Actions you tried yourself and if it works: 

- Not working: clear cookies, disable Javascript
- Working: archive.md

Browser (main version): Chrome 124.0.6367.63 (Official Build) (64-bit) on Windows 11

BPC-extension version (number): Bypass Paywalls Clean v3.6.6.3

DONE: PS always first search (domain) name in (all) issues (& use latest ext. version).
DONE: Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
A fix was already included in latest master (or next release).
