### ISSUE TITLE
Request [vocus.cc]

### ISSUE THREAD

**Issue by RaymondJSu** [bpc-clone/bpc_chrome_support#273]
Describe issue/request: new site request for Medium like website 

Link of paywalled article: [https://vocus.cc/article/66eb590bfd89780001eae1d1](https://vocus.cc/article/66eb590bfd89780001eae1d1)

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): clear cookies, disable JS, 12ft.io, clearthis.page

Browser (main version): Microsoft Edge Version 128.0.2739.79 (Official build) (64-bit)

BPC-extension version (number): v3.8.5.1

appreciate your help

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
