### ISSUE TITLE
Request [dn.se]

### ISSUE THREAD

**Issue by BrokenMirror-HNR** [bpc-clone/bpc_chrome_support#274]
Describe issue/request: new site request dn.se

Link of paywalled article: https://www.dn.se/varlden/har-fods-flest-barn-i-japan-men-det-finns-en-mork-historia/

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): clear cookies

Browser (main version): chrome newest

BPC-extension version (number): 3.8.4.5

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`\
PS import as custom site with Google Search Tool-fix.
