### ISSUE TITLE
Request [aftenposten.no]

### ISSUE THREAD

**Issue by BrokenMirror-HNR** [bpc-clone/bpc_chrome_support#275]
Describe issue/request: new site request aftenposten.no

Link of paywalled article: https://www.aftenposten.no/meninger/kommentar/i/Oo6vWk/abid-raja-og-danby-choi-er-for-pr-kaate

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): clear cookies

Browser (main version): chrome newest

BPC-extension version (number): 3.8.4.5

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`\
PS import as custom site with Google Search Tool-fix.
