### ISSUE TITLE
Request [Mediapart.fr]

### ISSUE THREAD

**Issue by Under66** [bpc-clone/bpc_chrome_support#276]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: New site request

Link of paywalled article: https://www.mediapart.fr/journal/france/250924/gouvernement-barnier-des-ministres-sous-influence 

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): clear cookies, disable javascript, reader view

Browser (main version): [Version 1.70.119 Chromium: 129.0.6668.70 (Build officiel) (64 bits)](https://brave.com/latest/)

BPC-extension version (number):  v3.8.5.2

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
PS import as custom site with Google Search Tool-fix.
