### ISSUE TITLE
Request: caixin.com

### ISSUE THREAD

**Issue by Desmondgeh** [bpc-clone/bpc_chrome_support#283]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: 
is it possible to add a new chinese site? 
Link of paywalled article: 
https://china.caixin.com/m/
Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

Browser (main version): 
kiwi
BPC-extension version (number): 
v3.8.5.0

**Comment by Desmondgeh** [comment]
or the URL for  a specific article
https://china.caixin.com/m/2024-09-27/102241024.html

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
