### ISSUE TITLE
Request: dircomfidencial.com

### ISSUE THREAD

**Issue by David-bcn** [bpc-clone/bpc_chrome_support#284]
Describe issue/request: 
   I have tried several options of the "Bypass Paywalls Clean" but I can't get past the paywall of the dircomfidencial.com domain.
   Some news are open and other news have a paywall, an example of a news with a paywall would be: 

https://dircomfidencial.com/medios/vocento-sigue-sin-acuerdo-para-nombrar-ceo-la-opcion-de-barrenechea-hoy-no-logra-mayoria-20240926-0405/

Link of paywalled article: https://dircomfidencial.com/medios/vocento-sigue-sin-acuerdo-para-nombrar-ceo-la-opcion-de-barrenechea-hoy-no-logra-mayoria-20240926-0405/

Browser (main version): Brave [Versión 1.70.119 Chromium: 129.0.6668.70 (Build oficial) (64 bits)]

BPC-extension version (number): Bypass Paywalls Clean 3.8.5.6

 Thanks,
 David.

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.

**Comment by David-bcn** [comment]
Hi bpc-clone, the truth is that I have tried all the options and I have not succeeded.
