### ISSUE TITLE
Request domain: ga4bigquery.com

### ISSUE THREAD

**Issue by Anna068** [bpc-clone/bpc_chrome_support#286]
Describe issue/request: New site request ga4bigquery.com

Link of paywalled article: https://www.ga4bigquery.com/how-to-fix-the-major-ga4-bigquery-export-misattribution-part-3-use-the-session_traffic_source_last_click-record/

Actions you tried yourself (mandatory) and if it works: clear cookies, archive sites. Sorry, I am not sure how to disable javascript, change user-agent/referer, reader view...

Browser (main version): Chrome 129.0.6668.71 (Official Build) (64-bit)

BPC-extension version (number): v3.8.5.7

**Comment by bpc-clone** [comment]
Site (ghost.io-domain) has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
