### ISSUE TITLE
Request [moneycontrol.com]

### ISSUE THREAD

**Issue by phantom-thread** [bpc-clone/bpc_chrome_support#289]
Describe issue/request: New site request

Link of paywalled article: https://www.moneycontrol.com/india/stockpricequote/power-generationdistribution/reliancepower/RP

Actions you tried yourself (mandatory) and if it works: clear cookies, disable javascript

Browser (main version): Version 1.70.123 brave browser
BPC-extension version (number): 3.8.6.3

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
