### ISSUE TITLE
Request: marketnews.com

### ISSUE THREAD

**Issue by xZ9v** [bpc-clone/bpc_chrome_support#29]
Describe issue/request: if possible, it would be great to add the financial website below in the extension

Links for the paywalled articles: 
MNI
https://marketnews.com/mni-fed-watch-powell-leans-into-higher-for-longer-not-hikes

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
 I tried to use some of the customs settings in the json file for other websites, but I didn't manage to get it working (the paywall splash screen was still blocking the content)

Browser (main version): Chromium on Linux

BPC-extension version (number):  Bypass Paywalls Clean v3.6.6.4  

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Add this filter to your adblocker (also in BPC filterlist):\
marketnews.com##+js(ra, class, div.body-description)

Update: domain also added as custom site to add-on (import from online).

**Comment by xZ9v** [comment]
OK great, thanks a lot. I managed to put your suggestion into the BPC settings as a custom script and it works well

**Comment by YesTrustMe** [comment]
> OK great, thanks a lot. I managed to put your suggestion into the BPC settings as a custom script and it works well

How did you get this to work? I am new to this and I don't know  where to paste to and what else I need to do. 

I'd like to learn how so I don't keep on asking for sites to be added to the custom list.
