### ISSUE TITLE
Request [newleftreview.org]

### ISSUE THREAD

**Issue by MedievalSteel** [bpc-clone/bpc_chrome_support#291]
Describe issue/request: Adding newleftreview.org to the list, Why remove?

Link of paywalled article: https://newleftreview.org/issues/ii148/articles/nathan-sperber-the-french-crisis-organic-or-conjunctural

Browser (main version): Chromium Version 122.0.6261.132 (Official Build) (64-bit)

BPC-extension version (number): v3.8.6.4

**Comment by bpc-clone** [comment]
Site was removed because Google webcache-fix no longer available.\
PS try do-it-yourself options from issue template (which you cut out).
