### ISSUE TITLE
Request: themorningcontext.com

### ISSUE THREAD

**Issue by shrimann3180** [bpc-clone/bpc_chrome_support#293]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: I would like to request bpc-clone team to add "themorningcontext.com" domain to the list of sites.

Link of paywalled article: https://themorningcontext.com/business/natco-just-cant-kick-its-high-risk-high-gain-game-plan

Actions tried : Cleared Cookies, js-disable, referrer changed- no luck, reader view doesn't work, unavailable in archived sites.

Browser (main version): Version 129.0.6668.90 (Official Build) (64-bit)

BPC-extension version (number): v3.8.6.6

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
