### ISSUE TITLE
asia.nikkei.com no longer working

### ISSUE THREAD

**Issue by nameless1643** [bpc-clone/bpc_chrome_support#294]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: BPC removed the subscription advertisement at the bottom of the Nikkei, but it seems unable to render the full text. There is no red warning of "Unable to obtain cache" at the top.

Link of paywalled article: https://asia.nikkei.com/Business/Startups/Singapore-s-Vertex-invests-in-Japanese-real-estate-data-provider

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Cleared Cookies, js-disable, referrer changed- no luck, reader view doesn't work, unavailable in archived sites（News before 10.7 can be obtained）.

Browser (main version):chrome 129.0.6668.90

BPC-extension version (number): v3.8.7.0

**Comment by nameless1643** [comment]
Thanks a lot, and could you explain a little more how this relates to the piano.js-script please？Did Nikkei close it intentionally?

**Comment by nameless1643** [comment]
> Indeed, but issue in site's piano.js-script. Wait & see if they fix it (nothing I can do about it).
> 
> PS full content available with Google Search Tool (no fix).

Thanks a lot, and could you explain a little more how this relates to the piano.js-script please？Did Nikkei close it intentionally?

**Comment by bpc-clone** [comment]
Site fixed in latest master/update rules (or next release).

**Comment by nameless1643** [comment]
> Site fixed in latest master/update rules (or next release).

The crx file of the kiwi browser does not seem to be automatically updated to the latest version(3.8.7.3).
