### ISSUE TITLE
Request/bug [morningstar.com]

### ISSUE THREAD

**Issue by FlyingFinn11** [bpc-clone/bpc_chrome_support#295]
Describe issue/request: Cannot access paywalled content across morningstar.com

Link of paywalled article: https://www.morningstar.com/best-investments

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): All methods tried. 

Browser (main version): Firefox 131.0

BPC-extension version (number): 3.8.6.1

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
