### ISSUE TITLE
Request: vccircle.com

### ISSUE THREAD

**Issue by dianetherese** [bpc-clone/bpc_chrome_support#297]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: Access to VCCircle

Link of paywalled article: https://www.vccircle.com/kkrcontrolled-bmh-group-appoints-former-mgm-fortis-hospital-exec-as-ceo

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): all

Browser (main version): https://www.vccircle.com

BPC-extension version (number): v3.8.7.0

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.\
PS for other issue: first search issues and/or `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
