### ISSUE TITLE
Request: newscientist.com

### ISSUE THREAD

**Issue by SGR21gtb** [bpc-clone/bpc_chrome_support#298]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: Full access to New Scientist (because not working or available yet)

Link of paywalled article: https://www.newscientist.com/article/2197040-most-powerful-thunderstorm-ever-measured-produced-1-3-billion-volts/

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Everything

Browser (main version): Chrome - 129.0.6668.90

BPC-extension version (number): 3.8.7.1

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`\
PS no need to request site which was removed recently (see changelog).

**Comment by Capt-Ahab726** [comment]
You stated that the site has a hard paywall but I accessed this site successfully just recently until you removed the site from the supported list.

**Comment by bpc-clone** [comment]
Don't mix up cause and effect: site was removed because Google webcache-fix is no longer available.

**Comment by SGR21gtb** [comment]
> Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)` PS no need to request site which was removed recently (see changelog).

sad
