### ISSUE TITLE
add support for babi.sh

### ISSUE THREAD

**Issue by mangzhu** [bpc-clone/bpc_chrome_support#302]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: 
bypass paywall on babi.sh

Link of paywalled article: 
https://www.babi.sh/recipes/sauces-9w5tm-2njph

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
tried clear cookies, reader view,

Browser (main version): 
Chrome 129.0.6668.90
BPC-extension version (number): 
v3.8.7.4

**Comment by bpc-clone** [comment]
Site was added to BPC adblocker filter; add these lines to your adblocker:\
`babi.sh##+js(ra, style, div[style*="filter:blur"], stay)`
`babi.sh##div[style="width: 100%; opacity: 1; transform: none;"]`
`babi.sh##div[style*="; overflow: hidden"][style*="; height:"]:style(height: 100% !important)`

**Comment by mangzhu** [comment]
thank you very much. The adblock fix half-worked. 

The begining part of the article is revealed but not the full article.

**Comment by bpc-clone** [comment]
Indeed, fixed by adding a third filter:\
`babi.sh##div[style*="; overflow: hidden"][style*="; height:"]:style(height: 100% !important)`

**Comment by mangzhu** [comment]
worked 100%.

Thank you very much!
