### ISSUE TITLE
Request  jn.pt

### ISSUE THREAD

**Issue by rigas40** [bpc-clone/bpc_chrome_support#305]
Describe issue/request:  If is possible this website to list, contry Portugal

Link of paywalled article:  https://www.jn.pt/4449620465/rui-moreira-ataca-governo-por-atraso-que-impede-videovigilancia-no-porto/

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site):  i try disable javascript

Browser (main version):  chrome last one

BPC-extension version (number):  3.8.7.4

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
