### ISSUE TITLE
Request to add parkiet.com

### ISSUE THREAD

**Issue by pdamiecki** [bpc-clone/bpc_chrome_support#315]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: paywall type should be the same as for https://www.rp.pl (already supported) - it is the same publisher

Link of paywalled article: https://www.parkiet.com/dywidendy/art41298371-rainbow-tours-wyplaci-dywidende-zaliczkowa

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): clearing cookies works for one article, next one viewed is paywalled

Browser (main version): Safari (ipadOS)

BPC-extension version (number): 3.8.7.2

**Comment by bpc-clone** [comment]
Site added in latest master (or next release).\
PS also in latest en-userscript.
