### ISSUE TITLE
Request to add seafoodsource.com

### ISSUE THREAD

**Issue by skinnerbka** [bpc-clone/bpc_chrome_support#320]
Describe issue/request: I'm wondering if it's possible to add _seafoodsource_ to the list of supported sites.

Link of paywalled article: https://www.seafoodsource.com/news/supply-trade/northeast-atlantic-pelagic-stocks-in-critical-danger-with-no-coastal-state-agreement-in-sight

Actions you tried yourself (mandatory) and if it works: _reinstalling extension, adding site to custom section, changing browser, clearing cookies_

Browser (main version): Yandex Browser 24.7.6.974 (latest)

BPC-extension version (number): v3.8.8.4

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
