### ISSUE TITLE
Request undercurrentnews.com

### ISSUE THREAD

**Issue by skinnerbka** [bpc-clone/bpc_chrome_support#322]
Describe issue/request: Is it possible to add _undercurrentnews_, or is it a hard paywall too?

Link of paywalled article: https://www.undercurrentnews.com/2024/10/18/cookes-culmarex-back-in-black-for-2023-with-strong-revenue-growth-profit-surge/

Actions you tried yourself (mandatory) and if it works: adding to the list of custom websites, clear cookies&permissions

Browser (main version): Yandex 24.7.6.974 (64-bit)

BPC-extension version (number): v3.8.8.5

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.\
PS always mention which custom options you tried.
