### ISSUE TITLE
investorschronicle.co.uk is not working

### ISSUE THREAD

**Issue by anderson0969** [bpc-clone/bpc_chrome_support#328]
Actions undertaken to resolve issue but not working (changelog and cookies cleared, latest version etc.)

Link of paywalled article:  https://www.investorschronicle.co.uk/content/896472d7-9b68-5e69-9407-5be561aa38ed

Browser (main version): Brave

BPC-extension version (number): 3.8.8.6.

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.\
PS always use full issue template.

Update: fix still working for most articles: link to Google Search Tool added for others.
