### ISSUE TITLE
Request: theinsneider.com

### ISSUE THREAD

**Issue by miba54** [bpc-clone/bpc_chrome_support#330]
Describe issue/request: theinsneider.com

Link of paywalled article: https://www.theinsneider.com/p/tom-holland-christopher-nolan-new-movie-vampire-rumor-mike-flanagan-carrie-series-amazon

Actions you tried yourself and if it works: cleared cookies, disabled javascript, tried reader view and archive sites, added as custom site - none worked.

Browser (main version): Chrome version 129.0.6668.101 (Official Build) (64-bit)

BPC-extension version (number): 3.8.9.2

**Comment by bpc-clone** [comment]
Site (beehiiv-blog) has hard paywall (no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
