### ISSUE TITLE
Request to add Crunchbase

### ISSUE THREAD

**Issue by shahmirulhaq** [bpc-clone/bpc_chrome_support#334]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: Requesting new website Crunchbase

Link of paywalled article: https://www.crunchbase.com/organization/crunchbase/company_financials

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site):  cleared cookies, disabled javascript, added as custom site

Browser (main version): Version 129.0.6668.90 (Official Build) (64-bit)

BPC-extension version (number):  v3.8.9.2

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.\
PS have you tried to login with a free account?

**Comment by shahmirulhaq** [comment]
Free account only works for a limited number of companies that can be shown
