### ISSUE TITLE
Request: Kinotico.es

### ISSUE THREAD

**Issue by CarlosLopezES** [bpc-clone/bpc_chrome_support#335]
Describe issue/request: https://kinotico.es

Link of paywalled article: https://kinotico.es/opinion/2024-10-25/homilia-vallin-bruja-escarlata-quiere-instalarse-tu-casa-para-negar-mundo

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site):  none worked. On clearthis.page, obtains text but it's not the full text, only three paragraphs.

Browser (main version): Chrome Versión 129.0.6668.101 (Build oficial) (64 bits) and Firefox 131.03

BPC-extension version (number): Bypass Paywalls Clean v3.6.5.2  

Thank you,

**Comment by bpc-clone** [comment]
Full text is contained in page source (Ctrl + u), but in different structure than supported by custom sites (can be reconstructed though).\
PS latest extension version: v3.8.9.6

Update: domain added as custom site (import & opt-in to custom sites); manual refresh of new page required.
