### ISSUE TITLE
Request test.de

### ISSUE THREAD

**Issue by cpy82** [bpc-clone/bpc_chrome_support#338]
Describe issue/request: test.de

Link of paywalled article: https://www.test.de/Kerninvestment-im-Portfolio-Muss-es-immer-MSCI-World-sein-6164684-0/

Actions you tried yourself (mandatory) and if it works: 
clear cookies: did not worked
disable javascript: did not worked
reader view: did not worked
archive sites: did not worked

Browser (main version): Chrome Version 130.0.6723.70 (Offizieller Build) (64-Bit)

BPC-extension version (number): 3.9.0.0

Thanks!

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
