### ISSUE TITLE
Request Lobservateur.fr

### ISSUE THREAD

**Issue by gosgtan** [bpc-clone/bpc_chrome_support#343]
Hello, 

Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe request: to remove paywall of articles from **lobservateur.fr**

Link of paywalled article: https://www.lobservateur.fr/nord-nouveaux-locaux-sidec-cambresis/

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site):
- clear cookies, disable javascript, reader view, archives sites, custom site. (does not work)

Browser (main version): Chrome, always up to date

BPC-extension version (number): 3.9.1.1

Ty

**Comment by bpc-clone** [comment]
Domain already supported as custom site (Group_fr_sogemedia): custom sites > import (from online) & opt-in to custom sites.
