### ISSUE TITLE
Rhein Zeitung isn't working anymore

### ISSUE THREAD

**Issue by lilaSchnitzel** [bpc-clone/bpc_chrome_support#347]
The website rhein-zeitung.de was updated the last few days. Since then, this previously perfectly fine working tool isn't working there anymore. I extra updated the extension to the latest version one or two days ago, which didn't help. But since it's only installed in my laptop, which ist at home and I'm writing this on my phone on the way to the university, I can't check for the version number right now.

**Comment by bpc-clone** [comment]
Googlebot-fix no longer works: site will be removed.\
PS always use issue template.

**Comment by lilaSchnitzel** [comment]
So no more bypassing possible here? :(
