### ISSUE TITLE
Request: breakingviews.com

### ISSUE THREAD

**Issue by Shang-1999** [bpc-clone/bpc_chrome_support#351]
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar)

request: request a new website https://www.breakingviews.com/

Link of paywalled article: https://www.breakingviews.com/considered-view/europe-lacks-scope-for-fiery-trump-trade-riposte/

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): I've tried all above but it doesn't work 

Browser (main version): Android  edge cCanary 132.0.2930.0

BPC-extension version (number): v3. 9. 1. 2

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
