### ISSUE TITLE
ESPN+ bypass no longer works for news articles

### ISSUE THREAD

**Issue by rbisker** [bpc-clone/bpc_chrome_support#352]
Describe issue/request:  No longer able to read ESPN+ articles in the USA.  This used to work via this plugin 

Links to examples of paywalled articles: 
- https://www.espn.com/mens-college-basketball/insider/story/_/id/42213965/jay-bilas-2024-25-mens-college-basketball-preview
- https://www.espn.com/nba/insider/story/_/id/42191100/nba-intel-trade-talk-milwaukee-embiid-updates-warriors 

I tried clearing cookies and updating BPC to the latest version.  Also tried disabling Ad Block Plus extension (even though it caused no issue previously)

Browser (main version): Chrome Version 130.0.6723.117 on Windows

BPC-extension version (number): 3.9.1.5

**Comment by bpc-clone** [comment]
Site fixed in latest master (or next release): content fetched from archive.is (use non-USA VPN).
