### ISSUE TITLE
This isn't work on japantimes.co.jp

### ISSUE THREAD

**Issue by minatahatsune** [bpc-clone/bpc_chrome_support#357]
Hello, I want to feedback that this plugin isn't work on [japantimes.co.jp](https://www.japantimes.co.jp/) as it should be (since it listed on the website list). When I access to japantimes.co.jp, it show a Bot Verification screen from Cloudflare, and when I ticked on the confirm checkbox, nothing happen and site keep loading forever.

I think someone met same problem here: https://www.reddit.com/r/Piracy/comments/1cmvrva/how_to_bypass_the_japan_times/

**Comment by bpc-clone** [comment]
Site fixed in latest master/update rules (or next release): reverted to old cookie-fix (do not block TinyPass-script).\
PS always use issue template.
