### ISSUE TITLE
chronicle.com no longer working

### ISSUE THREAD

**Issue by carstenknoch** [bpc-clone/bpc_chrome_support#366]
Fix recently stopped working. Changelog shows last update in 2022. They've changed their code.

Describe issue/request: Would love to get this working again!

Link of paywalled article: https://www.chronicle.com/article/is-it-time-to-regulate-ai-use-on-campus

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Tried all of these and was unable to see/read it.

Browser (main version): Edge 130.0.2849.80 (64 bit)

BPC-extension version (number): 3.9.2.0

**Comment by bpc-clone** [comment]
Site fixed in latest master/update rules (or next release).

**Comment by carstenknoch** [comment]
Terrific. Thanks, as ever.
