### ISSUE TITLE
Request weibo.com (ttarticle)

### ISSUE THREAD

**Issue by forkmax** [bpc-clone/bpc_chrome_support#367]
Describe issue/request: Request [https://weibo.com/ttarticle] 

Link of paywalled article: [https://weibo.com/ttarticle/p/show?id=2309405098127836185091]

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): all steps not work, including clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and add a custom site

Browser (main version): Google Chrome (latest version)

BPC-extension version (number): 3.9.1.7

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
