### ISSUE TITLE
seekingalpha.com no longer working

### ISSUE THREAD

**Issue by kartikpatel9** [bpc-clone/bpc_chrome_support#373]
Describe issue/request: 
Seeking alpha paywall removal doesn't work. It shows summary only and complete article fails to load.

Link of paywalled article: 
https://seekingalpha.com/article/4736029-roku-a-long-term-opportunity-amid-recent-drop
https://seekingalpha.com/article/4710422-roku-long-term-streaming-winner-facing-volatile-market-expectations
https://seekingalpha.com/article/4734247-tesla-stock-upgrade-elon-musk-just-got-a-new-job-at-the-doge

Actions you tried yourself 
- reload 10+ times
- clear cookies
- delete all browsing history 
- archive sites 
- tried downloading new bpc version at https://gitflic.ru/project/magnolia1234/bpc_uploads but install fails 

Browser (main version): Chrome Version 130.0.6723.117

BPC-extension version (number): v3.8.6.5

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
