### ISSUE TITLE
Request [storm.mg]

### ISSUE THREAD

**Issue by forkmax** [bpc-clone/bpc_chrome_support#374]
Describe issue/request: storm.mg

Link of paywalled article: https://www.storm.mg/article/5271117

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): all tried, but not work at all.

Browser (main version): chrome latest version

BPC-extension version (number): 3.9.3.0

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
