### ISSUE TITLE
Request cryptonary.com

### ISSUE THREAD

**Issue by mkster** [bpc-clone/bpc_chrome_support#376]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: 

Link of paywalled article: 
https://cryptonary.com/research/rebirth-of-solana-defi-ecosystem-breakdown/

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
tried clear cookies, disable javascript, and all the buttons, dunno how to do the others

Browser (main version): 
zen browser (firefox)

BPC-extension version (number): 
v3.9.2.0

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
