### ISSUE TITLE
thelawyer.com no longer working

### ISSUE THREAD

**Issue by Hdwi** [bpc-clone/bpc_chrome_support#384]
Describe issue/request: 

I would like to request for further support for [thelawyer.com](https://www.thelawyer.com/). The website has recently been updated, and BPC no longer seems to work as before.

Actions you tried yourself: 

- Cleared browser cookies and cache: Not working
- Disabled JavaScript: Not working
- Changed user-agent: Not working
- Used reader view: Not working
- Tried archive.is/archive.org: Not available
- Attempted to add as custom site: Not successful

(could be doing some of the steps wrong, or missing something)

Browser (main version): 

Chrome 131.0.6778.71

BPC-extension version (number): 
v3.9.3.6

**Comment by bpc-clone** [comment]
Site fixed in latest master (or next release).
