### ISSUE TITLE
Request eenews.net

### ISSUE THREAD

**Issue by paleomedia** [bpc-clone/bpc_chrome_support#385]
Describe issue/request: 

Link of paywalled article:  https://www.eenews.net/articles/doe-study-may-conclude-lng-worse-for-climate-than-coal-lobbyists-say/

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): tried archive.md/ph

Browser (main version): chrome

BPC-extension version (number): 3.9.3.6

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
