### ISSUE TITLE
Request: quest.nl

### ISSUE THREAD

**Issue by marcusdeman** [bpc-clone/bpc_chrome_support#39]
Describe issue/request: 

Link of paywalled article: 

https://www.quest.nl/mens/voeding/a60667462/plantaardige-eiwitten/

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

cleared cookies, disabled JS, etc.

Browser (main version): 

Chrome

BPC-extension version (number): 

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Actually use issue template: `request host permission for unlisted domain (by clearing cookies once by BPC-icon`\
Site works when you block general paywall-script of Piano.io/TinyPass
