### ISSUE TITLE
Request:  theguardian.com.au

### ISSUE THREAD

**Issue by bstafford57** [bpc-clone/bpc_chrome_support#391]
Describe issue/request: Can you please unblock the Swan Hill Guardian paywall.

Link of paywalled article: https://www.theguardian.com.au/feedback-sought-on-livestock-exchange

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Had no success adding as custom site

Browser (main version): Chrome 131.0.6778.86

BPC-extension version (number): 3.7.7.1

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
