### ISSUE TITLE
Bug telegraaf.nl metered paywall

### ISSUE THREAD

**Issue by roelsroels** [bpc-clone/bpc_chrome_support#392]
Describe issue/request: Telegraaf.nl has next to the premium articles (where BPC works fine!) a max # of views (per certain category) paywall implemented. Would be great if this can be fixed by BPC too. Basically this limit and thus the paywall appears on all non-premium articles after having opened a certain amount of them.

Link of paywalled article: https://www.telegraaf.nl/nieuws/1524173186/koortsachtig-overleg-in-de-coalitie-over-onderwijsbegroting-ergernis-over-inzet-nsc-minister-eppo-bruins

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site):  Clearing cookies and suggested options did not work for me, only loading it into an incognito browser fixes the paywall for the max # of reads of the article.

Browser (main version): Chrome 131.0.6778.86 on macOS 15.1.1

BPC-extension version (number): 3.9.4.0

See screenshot of the actual payway

<img width="1061" alt="Screenshot 2024-11-26 at 18 53 36" src="https://github.com/user-attachments/assets/71534756-0b49-4094-9edd-b28269b26ace">

**Comment by bpc-clone** [comment]
Site fixed in latest master (or next release).\
PS no cookie- or xhr-fix though, it seems.

**Comment by roelsroels** [comment]
Wow, that's fast! confirmed fixed, thanks! 👍🏼
