### ISSUE TITLE
Please fix  digital.lasegunda.com (La Segunda)

### ISSUE THREAD

**Issue by barbudo2005** [bpc-clone/bpc_chrome_support#393]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: 

The main page appears fine but when an article is opened, it appears without text.

Link of paywalled article: 

https://digital.lasegunda.com/2024/11/27/A/OG4GBQSI

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

Clear cookies, disable Adguard

Browser (main version): 

Chrome
Version 131.0.6778.86 (Official Build) (64-bit)

and 

Firefox 
132.0.2 (64-bit)

BPC-extension version (number): 

Chrome: 3.9.3.8
Firefox: 3.9.4

**Comment by bpc-clone** [comment]
Site has hard paywall now (no fix), it seems.

**Comment by barbudo2005** [comment]
It is not offline, please do not remove the site.

If it is not possible to fix it could you include this one?

https://www.lasegunda.com/
