### ISSUE TITLE
cw.com.tw not working anymore

### ISSUE THREAD

**Issue by n08ub** [bpc-clone/bpc_chrome_support#397]
Describe issue/request: 
This website was on the supported list, but it can't bypass anymore.

Link of paywalled article: 
https://www.cw.com.tw/article/5132909

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 
I've tried to update extension, clean cookies.

Browser (main version): 
Edge 131.0.2903.70 

BPC-extension version (number): 
3.9.5.0

**Comment by bpc-clone** [comment]
See options: `CommonWealth Magazine Taiwan (free articles only)`
PS 'no fix' message added in next release.
