### ISSUE TITLE
cmjornal.pt not working

### ISSUE THREAD

**Issue by charliefsilva** [bpc-clone/bpc_chrome_support#399]
Describe issue/request:

Website was currently supported, but bypass not working anymore.

Link of paywalled article:

https://www.cmjornal.pt/portugal/detalhe/advogada-denuncia-assedio-sexual-de-procurador-e-divulga-mensagens-de-magistrado

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site):

Clear cookies, disable Adblock, tried costum site, changed user-agent/referer

Browser (main version):

Edge 130.0.2849.99 (Official build) stable app, extended channel (64-bit)

BPC-extension version (number):

3.9.5.4

**Comment by bpc-clone** [comment]
Site has hard paywall (no more amp- fix): site will be removed.
