### ISSUE TITLE
Externalize domain/website bypass rules

### ISSUE THREAD

**Issue by skippybosco** [bpc-clone/bpc_chrome_support#4]
Describe issue/request: 

Currently add/change for websites/domains requires an update to the extension itself. Embedding the domain/websites within the extension also leaves it open to DMCA requests. 

Externalizing the ruleset via subscription to an external ruleset allows for more frequent updates to adapt to changing websites/domains without requiring users to refresh the extension so often. 

It may also allow for inclusion into the standard extension distribution channel (Chrome/Mozilla) as it will contain no rulesets on distribution, requiring end users to make a choice of how they choose to utilize the extension themselves.

**Comment by bpc-clone** [comment]
Sounds a lot like uBlock Origin, but there is already a BPC adblocker filterlist (works for way less sites than the extension).\
Part of the new sites and fixes can be updated by `Check for update rules at startup`, but this won't work for all sites.

I've had this advice before, but I still prefer a self-contained extension (partly by neccesity).\
A filterlist can also get a DMCA takedown notice though.
