### ISSUE TITLE
Request: allgaeuer-zeitung.de

### ISSUE THREAD

**Issue by FlorianAlexander** [bpc-clone/bpc_chrome_support#403]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: uses the same system as Augsburger-allgemeine.de (which works)

Link of paywalled article: https://www.allgaeuer-zeitung.de/allgaeu/windraeder-im-allgaeu-wo-sollen-windparks-entstehen-die-planung-ostallgaeu-flaechen-windkraftanlagen-103667008

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site):  unfortunately didnt work

Browser (main version): chrome 131

BPC-extension version (number): 3.9.6.7

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
