### ISSUE TITLE
Request: vccircle.com

### ISSUE THREAD

**Issue by sooding963** [bpc-clone/bpc_chrome_support#404]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: Can you please add this website to bypass paywall list

Link of paywalled article: https://www.vccircle.com/avendusset-to-hit-first-close-of-third-late-stage-investment-fund

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): I am unable too add it to the custom sites.

Browser (main version): [Chrome] 131.0.6778.141 

BPC-extension version (number): v3.9.0.7

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
