### ISSUE TITLE
Request theleaflet.in

### ISSUE THREAD

**Issue by SilentSparrow02** [bpc-clone/bpc_chrome_support#406]
Describe issue/request: Please bypass https://theleaflet.in/ premium articles

Link of paywalled article: https://theleaflet.in/analysis/how-fair-is-compensation-for-human-rights-violations-in-india

Actions you tried yourself (mandatory) and if it works: cleared cookies, disabled javascript, changed user-agent, reader view, archive sites, adding as custom site

Browser (main version): Chrome v131

BPC-extension version (number): 3.9.7.0

**Comment by bpc-clone** [comment]
Site added in latest master/update rules (or next release).

**Comment by SilentSparrow02** [comment]
You're a lifesaver! I really needed this for my college paper.
