### ISSUE TITLE
Request thejakartapost.com

### ISSUE THREAD

**Issue by Mukarouvsky** [bpc-clone/bpc_chrome_support#407]
request: Please bypass https://www.thejakartapost.com/ premium articles

Link of paywalled article: https://www.thejakartapost.com/opinion/2024/12/18/the-canary-in-the-gold-mine-greed-and-hypocrisy-threaten-sangihe.html

Actions you tried yourself: cleared cookies, disabled javascript, changed user-agent, reader view, archive sites, adding as custom site

Browser (main version): Chrome Version 131.0.6778.205 (Official Build)

BPC-extension version (number): 3.9.8.0

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`

**Comment by micha102** [comment]
Can bypass the sticky scrolling and the banner with this

if (matchDomain('thejakartapost.com')) {
	document.querySelector('meta[name*="is-premium"]').setAttribute("content","0");
	document.querySelector('div.tjp-paywall').remove();
}

**Comment by bpc-clone** [comment]
Before I was told: still no full article (by just removing the paywall-overlay), but maybe all premium articles are quite short.\
Same effect by adding adblocker filters:\
`||thejakartapost.com/skin/js/tjp-single.js$script,~third-party`
`thejakartapost.com##div.tjp-paywall`
