### ISSUE TITLE
Request malaysiakini.com

### ISSUE THREAD

**Issue by TanAHP** [bpc-clone/bpc_chrome_support#42]
Describe issue/request: 

Link of paywalled article: 
malaysiakini.com

Actions you tried yourself and if it works (clear cookies, disable Javascript, change user-agent/referrer, reader view, archive sites and/or add a custom site): 

tried all these: _**clear cookies, change user-agent/referrer, reader view, archive sites and/or add a custom site**_
doesn't work

Browser (main version): Edge 

BPC-extension version (number): 3.6.7.5

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
