### ISSUE TITLE
Request: 11freunde.de

### ISSUE THREAD

**Issue by KarateKaenguru** [bpc-clone/bpc_chrome_support#48]
Describe issue/request: Site was updated and completely changed 2 weeks ago, BPC didn't work before, could it work now maybe?

Link of paywalled article: https://www.11freunde.de/bundesliga/bundesliga-der-seltsame-fall-des-1-fc-union-a-87e1b405-b566-4a37-8608-b8bcb0268e54

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): tried to add it to custom sites but didn't quite understand what values to set

Browser (main version): Google Chrome, latest update

BPC-extension version (number): v3.6.7.1

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
