### ISSUE TITLE
Request: theloadstar.com

### ISSUE THREAD

**Issue by ljstyles92** [bpc-clone/bpc_chrome_support#52]
Describe issue/request: Add this site

Link of paywalled article: https://theloadstar.com/exclusive-kuehne-nagel-country-cluster-leads-revealed/

Actions you tried yourself and if it works (clear cookies, disable Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

Browser (main version): Chrome

BPC-extension version (number): 

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site is already is custom sites (import from online/local) & opt-in to custom sites.
