### ISSUE TITLE
Manifest version 2 is deprecated

### ISSUE THREAD

**Issue by pressslav** [bpc-clone/bpc_chrome_support#53]
Describe issue/request: 

I'm getting this error:

Manifest version 2 is deprecated, and support will be removed in 2024. See https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline for details.

Link of paywalled article: 

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

Browser (main version): Chrome Version 124.0.6367.208 (Official Build) (64-bit)

BPC-extension version (number): 

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Manifest v2 deprecation warning has been active for over a year now, but indeed for pre-stable versions of Chrome manifest v2 extension will stop working (without a ExtensionManifestV2Availability policy).

Before June I'll add a manifest v3 version for testing though.

Update: see new deprecation-issue (manifest v3 before Chrome 127/July 17h 2024).

**Comment by pressslav** [comment]
that makes sense, thank you!

**Comment by maiteemate** [comment]
Hello, I'm still getting the same error as the person who first opened it above.  Any updates on this? I'm trying to test this out on seekingalpha dot com site, and still no luck.  Please fix this as soon as you can., and post a comment here, once it's done, when you have some time.  Thank YOU Sir!
