### ISSUE TITLE
Request capitalbrief.com

### ISSUE THREAD

**Issue by ananyaburke** [bpc-clone/bpc_chrome_support#57]
Describe issue/request: To remove the paywall

Link of paywalled article: https://www.capitalbrief.com/article/dimensionals-australian-chief-on-the-11t-managers-systematic-active-approach-to-investing-9f785e7f-9d24-4c95-bfe1-a59c5c210870/

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): disabe Javascript, change user-agent/referer and archive sites

Browser (main version): Chrome 125

BPC-extension version (number): 3.6.8.2

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
