### ISSUE TITLE
Not showing the top half of the smh.com.au

### ISSUE THREAD

**Issue by AnthonyTheKoala** [bpc-clone/bpc_chrome_support#58]
**Issue**
Whaen you download the page from the smh.com.au, you only get the bottom half of the page.

**Link**
https://smh.com.au

**What it is supposed to be**
I had to use another browser eg duckduckho to display the heading.

![showing what it is supposed](https://github.com/bpc-clone/bypass-paywalls-chrome-clean/assets/26536316/f15f79a0-ad66-4832-99ca-136c3fa7c35d)

**What I actually get**
Using kiwi browser v 124.0.6327.4
I only get the remainder of the page. The top half is missing
![showing only bottom](https://github.com/bpc-clone/bypass-paywalls-chrome-clean/assets/26536316/f000866e-c697-4cd6-b457-d3054d46bacb)

**Temporary measure**
I go to the smh.com.au in the duckduckgo browser.
I find the article and copy the link and paste in the kiwi browser.

Thank you

**Comment by bpc-clone** [comment]
Confirmed, but not a BPC-issue: disable your adblocker (specific cosmetic filters) for the site on mobile.

**Comment by AnthonyTheKoala** [comment]
Dear developer,
The following disabling of the following apps did not resolve.
* switching off Ad Guard
* switching off all ad blocking on Kiwi browser
* switching off AVG Anti Virus
* switching off AVG Cleaner

Sum: switching off all these programs did not resolve the problem.

The same behaviour occurred on another mobile android phone.

Did not resolve the problem.

Thank you
________________________________
