### ISSUE TITLE
manifest file missing?

### ISSUE THREAD

**Issue by Meisel2** [bpc-clone/bpc_chrome_support#60]
I follow the instructions; I download the zip-file, unzip it, click load unpacked on the extensions page. However, I get the error message: "Manifest file is missing or unreadable." 

I've tried moving a bunch of files including manifest.json, background, bpc_count_daily_users and so on over from an older version and into the unzipped v.3.6.9.0 folder. I'm then able to install the extension, but then I end up with the older v.3.6.3.5. version and can't bypass several paywalls despite deleting all cookies. 

Browser: Google Chrome.

**Comment by bpc-clone** [comment]
Make sure you download the latest master zip-file mentioned in the installation instruction: https://github.com/bpc-clone/bpc_updates/releases/latest/download/bypass-paywalls-chrome-clean-master.zip

Repo is only used for support (not full source code).

**Comment by Meisel2** [comment]
Thanks it works. And I found the page where the latest master zip-files are posted
