### ISSUE TITLE
Request: nation.africa

### ISSUE THREAD

**Issue by emukus** [bpc-clone/bpc_chrome_support#62]
Describe issue/request: Hi, could you add support for Nation.Africa. It mostly covers East African news stories. Some articles are paywalled while others are not.

Link of paywalled article: https://nation.africa/kenya/news/how-geopolitics-influences-kenya-us-ties--4630348

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): I tried archive sites, and the article was not archived on any of them. I was not able to figure out how to add it as a custom site.

Browser (main version): Chrome 125.0.6422.61 (Official Build) (64-bit)

BPC-extension version (number): 3.6.9.0

**Comment by bpc-clone** [comment]
Site already supported as custom group_nation_media (import from local/online).

**Comment by emukus** [comment]
Ok, thank you
