### ISSUE TITLE
No longer works for penews.com

### ISSUE THREAD

**Issue by cellestial221** [bpc-clone/bpc_chrome_support#63]
Describe issue/request: New site request- Private Equity News

Link of paywalled article: https://www.penews.com/articles/eqt-could-exit-nord-anglia-in-deal-valued-up-to-15bn-latest-deal-pipeline-20240307

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Yep have tried all, am blocked when using googlebot too

Browser (main version): 125.0.6422.61

BPC-extension version (number): 3.6.9.2 

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Googlebot-fix no longer works: site will be removed from extension.
