### ISSUE TITLE
New website request:  Messari.io

### ISSUE THREAD

**Issue by amiralinsr** [bpc-clone/bpc_chrome_support#65]
_Describe issue/request:_ 
I'd like to pass Messari.io's paywall articles. I tried all the things mentioned in the readme file, It didn't work.

_Link of paywalled article:_ 
https://messari.io/report/state-of-smart-contract-platforms-q1-2024
(pretty much all the pro and enterprise articles that are found in "Research" tab)

_Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site):_ 
all these below, although Im not quiet understand all the custom website section's settings. I tried a multiple combos but non has worked.
> Open incognito window and search for article in Google search (or webcache).
Clear cookies for the site (by this extension: opt-in to custom sites or grant host permission for the site; also enables blocking of general paywall scripts).
Disable Javascript on the site (by browser, uBlock Origin or other extension).
Add the domain as custom site for more bypass options.
Open page in reader view (by browser or extension).
Try one of the archive sites:

_Browser (main version):_ 
Chrome Version 124.0.6367.210 (Official Build) (64-bit)
_BPC-extension version (number):_ 
v3.6.9.2
_PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix._

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.
