### ISSUE TITLE
Request: ville-rail-transports.com

### ISSUE THREAD

**Issue by JulienL-01** [bpc-clone/bpc_chrome_support#67]
Describe issue/request: paywall not removed

Link of paywalled article: https://www.ville-rail-transports.com/ferroviaire/le-mp59-quitte-le-metro-parisien-apres-60-ans-de-service/

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): everything listed here

Browser (main version): Google Chrome 125.0.6422.77

BPC-extension version (number): Bypass Paywalls Clean v3.6.9.3

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site added to custom sites (import from online & opt-in to custom sites).

**Comment by JulienL-01** [comment]
Sorry for the delay!
I tried with custom site but it didnt work.. so you have a tuto on how to do it for this specific website? 
Thanks a lot,
