### ISSUE TITLE
Request: businessdesk.co.nz

### ISSUE THREAD

**Issue by JustSomeGuyNZ** [bpc-clone/bpc_chrome_support#71]
Describe issue/request: BusinessDesk is part of the same stable as New Zealand Herald (NZME) but is still paywalled.

Link of paywalled article: https://businessdesk.co.nz/article/politics/millions-in-the-mist-funds-for-foreign-affairs-cloud-project-allegedly-mismanaged

Actions you tried yourself and if it works: Tried custom site with, disabe Javascript (didn't work), change user-agent/referer (cloudflare blocked). Happy to try more but don't really know what I'm doing lol.

Browser (main version): Vivaldi | 6.7.3329.31

BPC-extension version (number): 3.7.0.0

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
