### ISSUE TITLE
Request: caravanmagazine.in

### ISSUE THREAD

**Issue by samsa-mandico** [bpc-clone/bpc_chrome_support#73]
Describe issue/request: 

Link of paywalled article: https://caravanmagazine.in/politics/tyranny-will-worsen

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): cleared cookies, tried reading mode (both edge and firefox), used bpc, etc.

Browser (main version): Microsoft Edge (Version 125.0.2535.67)

BPC-extension version (number): 3.7.0.0

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
