### ISSUE TITLE
Request: epw.in

### ISSUE THREAD

**Issue by samsa-mandico** [bpc-clone/bpc_chrome_support#74]
Describe issue/request: Can't access any articles, hitting paywall

Link of paywalled article: https://www.epw.in/journal/2024/21/special-articles/towards-tax-justice-and-wealth-redistribution.html

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Cleared cookies, tried reader mode (both Edge and Chrome), BPC
Browser (main version): Microsoft Edge (Version 125.0.2535.67)

BPC-extension version (number): 3.7.0.0

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
