### ISSUE TITLE
Fiskeribladet.no suddenly stopped working

### ISSUE THREAD

**Issue by skinnerbka** [bpc-clone/bpc_chrome_support#75]
_Describe issue/request:_ 
Fiskeribladet paywalled pages not working

_Link of paywalled article:_ 
https://www.fiskeribladet.no/okonomi/russisk-torsk-hvitvaskes-i-norge-for-den-selges-tollfritt-til-eu/2-1-1645419
https://www.fiskeribladet.no/okonomi/rederi-fikk-800-000-kroner-i-bot/2-1-1648684

_Actions you tried yourself and if it works (clear cookies, disable Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site):_ 
Did everything listed as a possible solutions. Multiple times. 

_Browser (main version):_ 
Chrome 125.0.6422.113

_BPC-extension version (number):_ 
v3.7.0.1  

Screenshot of the paywalled page not loading properly
![Безымянный](https://github.com/bpc-clone/bypass-paywalls-chrome-clean/assets/171021033/079338fe-051a-4d9d-9264-05c24b215ef9)

I would like to say a special big thank you for this extension. 

Regarding the problem: this site used to work fine, it is listed as supported (NHST Media Group sites) but about a week ago something broke.

**Comment by bpc-clone** [comment]
New paywall for most sites of NHST Group fixed in latest master (or next release).
