### ISSUE TITLE
Fails on staradvertiser.com

### ISSUE THREAD

**Issue by raybies808** [bpc-clone/bpc_chrome_support#8]
Describe issue/request: Stopped working on staradvertiser.com paywalled articles starting this week.

Link of paywalled article: https://www.staradvertiser.com/2024/04/24/hawaii-news/gov-green-pledges-to-sign-short-term-rentals-bill/

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): 

None of these worked:
Cleared cookies
Disabled Javascript
Add custom site
Incognito mode
Tried both in Chrome and Edge

Browser (main version):
Chrome Version 124.0.6367.79
Edge Version 124.0.2478.51 

BPC-extension version (number): 3.6.5.3

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site fixed in latest master/update rules (or next release)

**Comment by raybies808** [comment]
It's working, thank you!
