### ISSUE TITLE
Courrier international blocked again

### ISSUE THREAD

**Issue by christoic** [bpc-clone/bpc_chrome_support#82]
Describe issue/request: 

https://www.courrierinternational.com/
Pay wall not removed (was working 2 weeks ago)

Link of paywalled article: 
https://www.courrierinternational.com/article/psychologie-que-font-les-gens-heureux-ils-mettent-de-l-argent-de-cote

Clear cookies, disable block ads (kiwi browser),diable ublocker

Browser (main version): Kiwi Browser 124.0.6327.4

BPC-extension version (number): 3.7.0.0

**Comment by bpc-clone** [comment]
Already fixed in latest master (or next release): see changelog.
