### ISSUE TITLE
Chrome 127 (July 17th 2024) will disable manifest v2 extensions soon

### ISSUE THREAD

**Issue by bpc-clone** [bpc-clone/bpc_chrome_support#84]
Chrome 127 (expected July 17th 2024) will probably disable manifest v2 extensions soon: https://developer.chrome.com/blog/resuming-the-transition-to-mv3
Before that date a manifest v3 version of the BPC-extension will be released for testing.

Pre-release Chrome version may block manifest v2 extensions sooner (June 2024): https://chromestatus.com/roadmap

By setting the ExtensionManifestV2Availability policy you can postphone this for a year though: https://chromeenterprise.google/policies/#ExtensionManifestV2Availability

Example ExtensionManifestV2Availability.reg file for Chrome main release:
```
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome]
"ExtensionManifestV2Availability"=dword:00000002
```

**Comment by SGR21gtb** [comment]
And in 2025 we have to update this to V3.

**Comment by bpc-clone** [comment]
https://www.ghacks.net/2024/10/16/google-chrome-removal-of-ublock-origin-and-other-unsupported-extensions-has-started

**Comment by bpc-clone** [comment]
BPC extension updated to manifest v3 (v3.8.9.0) !
