### ISSUE TITLE
Request limelight-arts.com.au

### ISSUE THREAD

**Issue by danielgruber8** [bpc-clone/bpc_chrome_support#87]
Describe issue/request:  unblock subscriber articles

Link of paywalled article:  https://limelight-arts.com.au/features/havasi-pop-star-prince-of-pure-piano/
https://limelight-arts.com.au/features/mother-lode/

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): incognito mode

Browser (main version):  Google Chrome 125.0.6422.141 (Official Build) (64-bit) 

BPC-extension version (number): Bypass Paywalls Clean v3.7.0.0  

PS: Welcome back.

**Comment by bpc-clone** [comment]
Site has hard paywall (no fix), it seems.\
PS next time use DIY-options first.
