### ISSUE TITLE
Request thecurrent.com/OpenPass

### ISSUE THREAD

**Issue by LtPatterson** [bpc-clone/bpc_chrome_support#9]
Describe issue/request: Thecurrent.com has enabled "openpass" authentication to read articles. This is an authentication standard being rolled out on publisher sites to collect user data and block access.

Link of paywalled article: https://www.thecurrent.com/google-chrome-cookie-deprecation

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Adblock on or off, clear cookies/cache, archive sites do work - https://archive.ph/u6NCp.

Browser (main version): Chrome 124.0.6367.79

BPC-extension version (number): 3.6.5.5

PS always first search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Regwall overlay can be removed by adding this filter to your adblocker:\
thecurrent.com##div#headlessui-portal-root
