### ISSUE TITLE
Please add this site: Law360.com

### ISSUE THREAD

**Issue by ljstyles92** [bpc-clone/bpc_chrome_support#91]
Describe issue/request: Add the website

Link of paywalled article: https://www.law360.com/articles/1844927/abbott-asks-upc-to-nix-dexcom-glucose-monitor-patent

Actions you tried yourself and if it works (clear cookies, disabe Javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): Using ur custom sites option, allowed cookies, changed user-agent to Google

Browser (main version):  Chrome

BPC-extension version (number): 

PS always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix).

**Comment by bpc-clone** [comment]
Site has hard paywall( no fix): `request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
