### ISSUE TITLE
Please add thelocal.fr

### ISSUE THREAD

**Issue by alinsfgit** [bpc-clone/bpc_chrome_support#96]
Can you please add https://www.thelocal.fr/

Disabling JavaScript opens up articles but messes with images and formatting.

Browser: Latest Edge on Windows 11

BPC-extension version: 3.7.1.1

Thank you!

**Comment by bpc-clone** [comment]
Site (& group) just uses general paywall script (TinyPass): `first request host permission for unlisted domain (by clearing cookies once by BPC-icon; X = no fix)`
